### ISSUE TITLE
Switch css variables plugin for something that closer resembles current evergreen browser functionality

### ISSUE THREAD

**Issue by mike-rotate** [csstools/postcss-preset-env#101]
Would it be possible to switch out the default css variables plugin [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties), which is quite conservative in what it functionality it covers, for another plugin that provides closer functionality to what the current evergreen browsers offer, e.g. [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables).

Reason: I would like to polyfill css variables in ie 11 whereby i can still create a variable outside the :root selector and later modify said variable in a media query.

**Comment by jonathantneal** [comment]
I understand your concern, but please do read up on the differences between the two plugins. The choice is very deliberate.

While this doesn’t substitute the research I recommend, just know that we cannot safely determine non-root custom properties. Switching to the other plugin would not respect evergreen browsers or the spec, and it could produce inconsistent results.
