### ISSUE TITLE
Configuration cssnano optimisations based on browserlist?

### ISSUE THREAD

**Issue by leimonio** [csstools/postcss-preset-env#106]
`ccsnano` offers some configurable optimisations, like [`calc`](https://cssnano.co/optimisations/calc). Is there a way to use the browserlist other than polyfilling to also configure these optimisations?

To give some more context, using webpack with `optimize-css-assets-webpack-plugin` for production builds results in transforming `calc(100vh - 5rem - calc(10rem + 100px))` to `calc(100vh - 5rem - 10rem + 100px)`.

**Comment by jonathantneal** [comment]
This seems like an issue for cssnano. They can add support for browserslist, certainly. I can certainly provide any guidance from my integration experience.
