### ISSUE TITLE
Order of CSS variable definitions matter, should they?

### ISSUE THREAD

**Issue by seanforyou23** [csstools/postcss-preset-env#109]
Hello, thank you for this library! I'm currently trying to use it to transform some CSS to an older format. Generally, it works great. The one thing I'm finding problematic is that the CSS variable definitions matter and must come before their respective variable references.

With CSS variables, it's possible to make references to variables before they are defined as these variable definitions are hoisted allowing one to write CSS in a way that makes sense logically for the application, without being constrained by maintaining a specific source order.

In other words, one of the benefits of CSS vars is they can be used non-linearly. When postcss-present-env encounters such a case, it results in `undefined` being generated as the value.

Is this intentional? Is it a bug? If it's not considered a bug, is this by chance a feature you'd be willing to add? The alternative for our team is that we'd have to take on the undue burden of structuring our CSS to be vars first, which for us over in [patternfly](https://github.com/patternfly/), would not be ideal.

Apologies in advance if I've overlooked some configuration or technique that already allow for this.

Please let me know if there's anything I can help do to move this forward. Thank you!!

**Comment by jonathantneal** [comment]
Hi @seanforyou23, I’m not sure which version of this project you are using, as I believe this has always worked.

For instance, I tested the following CSS on https://preset-env.cssdb.org/playground using the browserslist `ie >= 11` (added to the text field on the upper right):

```pcss
body {
  font-size: var(--default-font-size);
}

:root {
  --default-font-size: 1rem;
}
```

It produced the following result:

```css
body {
  font-size: 1rem;
  font-size: var(--default-font-size);
}

:root {
  --default-font-size: 1rem;
}
```

The plugin that powers this functionality, postcss-custom-properties, checks for all `:root` rules before transforming Custom Properties.

Here is the line where it reads `:root` Custom Properties: https://github.com/postcss/postcss-custom-properties/blob/master/index.js#L23

And here is the line where it applies them through the CSS: https://github.com/postcss/postcss-custom-properties/blob/master/index.js#L28

**Comment by seanforyou23** [comment]
@jonathantneal thank you for such a quick reply! So, I'm seeing the same thing you describe on my end, and the vars defined within `:root {}` are working just fine from what I can tell. I realize now I left out an important detail, which is that we're using component level variables as well as `:root {}` level variables. For example, try running this in the playground.

```body {
  font-size: var(--default-font-size);
  font-size: var(--new-font-size);
}

:root {
  --default-font-size: 1rem;
}

.some-module {
 --new-font-size: 2rem;
}```

It results in 

```body {
  font-size: 1rem;
  font-size: var(--default-font-size);
  font-size: var(--new-font-size);
}

:root {
  --default-font-size: 1rem;
}

.some-module {
 --new-font-size: 2rem;
}```

Notice the new value of `2rem` isn't applied to body, although the css variable does exist. Does this make sense?

**Comment by jonathantneal** [comment]
Ah, this is a very common limitation run into by developers. Imagine the following HTML:

```html
<div class="some_component">
  <h1>Hello World</h1>
</div>
```

Imagine it uses the following CSS:

```
* {
  --font-size: 16px;
}

:root {
  --font-size: 20px;
}

.some_component {
  --font-size: 24px;

  & h1 {
    font-size: calc(var(--font-size) * 1.5));
  }
}
```

The `<h1>` will be `24px` because `*` was the nearest element with the `--font-size` Custom Property.

At built time, we can never _know_ which Custom Properties should be used outside of `:root` or `html`, and so we ignore Custom Property declarations made within other elements. This is a significant limitation that could produce unexpected results in IE browsers. However, this is also a limitation that many developers have been willing to live with and offset as needed.

**Comment by seanforyou23** [comment]
@jonathantneal thank you for explaining the reasoning. Really helps. In case we were to find a way to make this work safely and predictably, would you be open to accepting a PR to make it happen?

**Comment by jonathantneal** [comment]
Yes, I would be open to such a PR. Sure, I might be hesitant to add something like all of JSDOM to the project, if that was what was required, but I’d entertain any thought out solution.

I’ll be closing this immediate issue, but by all means we can continue the discussion.
