### ISSUE TITLE
Need update of autoprefixer dependency to 9.4.5

### ISSUE THREAD

**Issue by RandomPiche** [csstools/postcss-preset-env#112]
Hi, would you mind adding autoprefixer 9.4.5 to the dependencies as it adresses a webpack warning that I can't get rid of ? 
post-preset-env is the only dependency requiring autoprefixer 9.4.2 that my project relies on.
https://github.com/postcss/autoprefixer/issues/1179

Issue fixed in https://github.com/postcss/autoprefixer/releases/tag/9.4.5

Thanks for considering my request ! Keep up the good work 🙏

**Comment by jonathantneal** [comment]
This has been fixed and published in 6.6.0.
