### ISSUE TITLE
Need to add scroll to code samples on website

### ISSUE THREAD

**Issue by Semigradsky** [csstools/postcss-preset-env#115]
![screenshot_2019-01-28-19-30-02-608_com android chrome](https://user-images.githubusercontent.com/1198848/51850842-ab8d9e00-2333-11e9-834f-eac8dd1c2e85.png)
https://preset-env.cssdb.org/features

**Comment by yepninja** [comment]
https://github.com/csstools/postcss-preset-env-www/pull/8

**Comment by philipbordallo** [comment]
@yepninja is right but those changes don't seem to be live on https://preset-env.cssdb.org/

**Comment by jonathantneal** [comment]
I will, yes. I can’t tonight. I’m not feeling very well. 😞

**Comment by jonathantneal** [comment]
This has been fixed. I am sick again, btw, so funny how that works. 😄
