### ISSUE TITLE
Media Queries not working

### ISSUE THREAD

**Issue by waynehaffenden** [csstools/postcss-preset-env#121]
I have been pulling my hair out trying to get this working, I'm no doubt probably missing something here so hoping you can help me. I have the latest version of postcss-preset-env installed (v6.6.0) and here is my postcss.config.js file:

```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      stage: 1,
      features: {
        'nesting-rules': true
      }
    },
    'cssnano': {
      autoprefixer: false
    }
  }
};

```

My CSS is as follows:

```css
:root {
  @custom-media --breakpoint-xxl (min-width: 1920px);
  @custom-media --breakpoint-xl (min-width: 1680px) and (max-width: 1919px);
  @custom-media --breakpoint-l (min-width: 1280px) and (max-width: 1679px);
  @custom-media --breakpoint-m (min-width: 960px) and (max-width: 1279px);
  @custom-media --breakpoint-s (min-width: 640px) and (max-width: 959px);
  @custom-media --breakpoint-xs (min-width: 320px) and (max-width: 639px);
  @custom-media --breakpoint-xxs (max-width: 320px);
}

@media (--breakpoint-xxl) {
  /* do something */
}
```

They are just not being processed and are outputted in the resulting CSS file untouched. Any ideas?

**Comment by equinusocio** [comment]
Mmm your mq are a bit messy. You can simplify them like this:

```css
:root {
  @custom-media --breakpoint-xxl (min-width: 1920px);
  @custom-media --breakpoint-xl (min-width: 1680px);
  @custom-media --breakpoint-l (min-width: 1280px);
  @custom-media --breakpoint-m (min-width: 960px);
  @custom-media --breakpoint-s (min-width: 640px);
  @custom-media --breakpoint-xs (min-width: 320px);
  @custom-media --breakpoint-xxs (max-width: 320px); /* You don't need this .*/
}

```

**Comment by jonathantneal** [comment]
@waynehaffenden, your `@custom-media` need to exist outside `:root`, not within it. That should clear things up.

@equinusocio, while those read a bit cleaner, your corrections lack the max width. Maybe that’s not how you like to write media queries, but we can be cool with adding them back in _and_ keeping them short with Media Query Ranges.

```pcss
@custom-media --breakpoint-xxl (width >= 1920px);
@custom-media --breakpoint-xl (1680px <= width < 1920px);
@custom-media --breakpoint-l (1280px <= width < 1680px);
@custom-media --breakpoint-m (960px <= width < 1280px);
@custom-media --breakpoint-s (640px <= width < 960px);
@custom-media --breakpoint-xs (320px <= width < 640px);
@custom-media --breakpoint-xxs (width < 320px);
```

**Comment by waynehaffenden** [comment]
@equinusocio Thank you for all your help!

@jonathantneal Thank you so much, I knew it'd end up being something really simple in the end, wasted many hours trying to figure it out. Also, thank you for the cleaner code too.
