### ISSUE TITLE
Confusing use of postcss-initial

### ISSUE THREAD

**Issue by dalgard** [csstools/postcss-preset-env#124]
Figuring out that `postcss-initial` [is included](https://github.com/csstools/postcss-preset-env/blob/d81eb93d8df554af1e9029c3bf89b2da70cbf2d3/src/lib/plugins-by-id.js#L37) as the so called _all property_ feature isn't totally straightforward.

Neither is the fact that it can be configured under the id `all-property` – or so I've come to assume, anyway.

**Comment by jonathantneal** [comment]
I agree. The feature should be named `initial-value` or `initial-keyword` and the caniuse for it should be `css-initial-value`. This bug should be fixed in https://github.com/csstools/cssdb/blob/master/cssdb.json#L2-L19

**Comment by jonathantneal** [comment]
I would need help to actually address this issue. It seems like a breaking change.

**Comment by romainmenke** [comment]
Going to close this issue but I have [started a discussion here](https://github.com/csstools/postcss-plugins/discussions/86) to see how we can do better in making the naming clear and easy to use.
