### ISSUE TITLE
Documentation website broken on Firefox

### ISSUE THREAD

**Issue by natecox** [csstools/postcss-preset-env#125]
### Problem
The syntax highlighting on the doc website isn't functional on Firefox 68.0b2 64-bit (Developer edition, standard not tested), rendering the examples essentially illegible.

### OS, errata
Item | Value
-----|-----
OS | macOS 10.14.5 Beta (18F127a)
Browser | Firefox Developer Edition 68.0b2 (64-bit)

### Demo
![image](https://user-images.githubusercontent.com/2782695/58113462-67582f00-7baa-11e9-9419-4a939734e561.png)

**Comment by fabswt** [comment]
Still the same a year later in Firefox 75.

**Comment by chrishrtmn** [comment]
I think the website is just out of date. I also made an issue regarding the Stages not matching up with where they are in the Specifications now: https://github.com/csstools/postcss-preset-env/issues/182

**Comment by jherdman** [comment]
FYI this is still a problem in FF82. How can we help?

**Comment by bdurrer** [comment]
I don't have issues with the colors on 90.0 as of July 2021, maybe it _was_ fixed?

BUT: On firefox it is impossible to select a stage in the dropdown, it closes immediately when moving the mouse.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
