### ISSUE TITLE
PostCSS Custom Properties v9

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#131]
https://github.com/postcss/postcss-custom-properties

- [ ] Node 8+ compatibility
- [ ] PostCSS Values Parser 3+ compatibility
- [ ] Use PostCSS Custom Utils

**Comment by BPScott** [comment]
Heya @jonathantneal,

I've just ran into a case with some css that threw an error in postcss-custom-properties v8 but works correctly in v9 (https://github.com/Shopify/polaris-react/issues/2629).  I was wondering if cutting a release with the updated postcss-custom-properties (and probably all the other dependant packages thanks to dropping node 6) was something you're working on any time soon?

**Comment by romainmenke** [comment]
Plugin has been updated.
