### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by ai** [csstools/postcss-preset-env#134]
@jonathantneal `postcss-preset-env` with latest `caniuse-lite` generates a wrong query `android all` and send it to Browserslist

https://github.com/browserslist/browserslist/issues/382

Fix affects all CRA, Nuxt.js, etc users.

**Comment by ai** [comment]
I released a very dirty fix (just ignore `android all`) in Browserslist 4.6.3.

Lock Browserslist to 4.6.2 to test and fix the source of the issue.

**Comment by Pearyman** [comment]
![image](https://user-images.githubusercontent.com/6932025/59671240-ec595700-91ef-11e9-921e-20145fb9cad6.png)

It works , but lots of  consoles

**Comment by timurmamedov** [comment]
Thanks for making a quick fix @ai 👍Just a note that creating static react app builds with CRA is impossible atm with this fix as it never concludes the script.

**Comment by jonathantneal** [comment]
How is `android all` being generated?

**Comment by ai** [comment]
@jonathantneal I have no idea too :(. Here is stacktrace:

```
{ BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:204:10)
    at /home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:296:11
    at Array.reduce (<anonymous>)
    at resolve (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:237:18)
    at browserslist (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:361:16)
    at browserslist (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:92:24)
    at Array.some (<anonymous>)
    at some (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:91:32)
    at Array.filter (<anonymous>)
    at filter (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:90:43)
    at creator (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss/lib/postcss.es6:111:34)
    at config.plugins.sortPlugins.map (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4168:18)
    at Array.map (<anonymous>)
    at PostcssConfig.loadPlugins (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4162:10)
    at PostcssConfig.config (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4198:14)
    at StyleLoader.postcss (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4255:39)
  name: 'BrowserslistError',
  message:
   'Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.',
  browserslist: true }
```

**Comment by ai** [comment]
Yeap, current PR is not really fix the problem (it just force Browserslist with dirty fix to ignore `android all`).

BTW, `all` is a version of Opera Mini and some Chinese browsers on Can I Use. So `op_mini all` is a correct query.

Maybe it shows the right way? Maybe in `postcss-preset-env` somehow version from Opera is used for Android?

**Comment by jonathantneal** [comment]
Here is a fully documented version of how I take a caniuse id and extrapolate all of the browsers that I will match against.

https://gist.github.com/jonathantneal/fb625b55e94709a8763802b0baea075b

With that as a reference, caniuse is now providing a `version` ([see line 21](https://gist.github.com/jonathantneal/fb625b55e94709a8763802b0baea075b#file-getunsupportedbrowsersbycaniuseid-js-L21)) with a value of `all` which is added to the query list ([see line 28](https://gist.github.com/jonathantneal/fb625b55e94709a8763802b0baea075b#file-getunsupportedbrowsersbycaniuseid-js-L28))

**Comment by ai** [comment]
So `caniuse-db` started to add `all` to `android`? But I found separated versions in `caniuse.agents.andoid` and on the website.

**Comment by jonathantneal** [comment]
Yes. You can test this yourself with the following code.

```js
// get all caniuse data
const caniuse = require('caniuse-lite');

// get compressed caniuse feature details for "css-all"
const featureDetails = caniuse.features['css-all'];

// get caniuse stats for "css-all"
const { stats } = caniuse.feature(featureDetails);

// log caniuse "css-all" stats for "android" and see version "all"
console.log(stats.android);
```

An unstable fix would be to add a line that replaces any `value` of `all` with ` > 0`.

```suggest
version = version === 'all' ? '> 0' : version;
```

I say “_unstable_” because caniuse made an architectural change in a non-breaking release, so what would stop that from happening again. 🤷‍♀

**Comment by jonathantneal** [comment]
It looks like `caniuse` or `caniuse-lite` may have published a potentially breaking change that rolled into `postcss-preset-env`, which then rolled into `browserslist` and threw this error or warning.

**How it worked**: More or less, caniuse stats are provided as an object of features, like `{ "css-all": {}, "css-any-link": {} }`. Within each feature, stats are provided as an object of browsers, like `{ "android": {}, "edge": {} }`. Within each browser, stats are provided as an object of versions or version ranges, like `{ 4.1": "n", "4.2-4.3": "n" }`.

For example, one tree of features might look like `{ "css-all": { "android": { "4.1": "n", "4.2-4.3": "n" } } }`.

**What changed**: Within the `android` browser object of versions, stats now provide a simplified `"all"` value.

This means one tree of features might look like `{ "css-all": { "android": { "all": "n" } } }`.

That is how the `android all` query ends up getting generated, which browserslist does not support.

**Comment by ai** [comment]
> It looks like caniuse or caniuse-lite may have published a potentially breaking change that rolled into postcss-preset-env, which then rolled into browserslist and threw this error or warning.

Yeap. Can I Use policy is database is just an as-is dump :(.

> This means one tree of features might look like { "css-all": { "android": { "all": "n" } } }.

Is it just for one feature? Maybe it is somebody bug in feature JSON?

If it is not a single bug, we can do one of these changes:

1. Add `ignoreUnknownVersions` to `browserslist()` call.
2. Replace `all` to all version from `caniuse.agents`

**Comment by csi-lk** [comment]
Can confirm using:

```json
  "resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  }
```

works around the issue for the moment

**Comment by ai** [comment]
@jonathantneal what method did you decide to use to fix this?

**Comment by testcderick** [comment]
Builds is okay now, since the latest update to caniuse-lite from 5 hours ago.

Update the version of caniuse 1.0.30000976 and everything will be fine.

**Comment by ai** [comment]
Did Can I Use fixed their broken feature JSON? Do you see warnings from Browserslist?

Anyway we need to find a way to avoid same but in the future.

Preset Env should not trust to Can I Use feature JSONs and be ready for non-existed browsers.

**Comment by jonathantneal** [comment]
> Did Can I Use fixed their broken feature JSON?

1. Yes, they appear to have removed the `all` version from in caniuse-db@1.0.30000976, which was then merged into caniuse-lite@1.0.30000976.
2. Hmm, “broken” is subjective, as there may not have been any schema for caniuse-db JSON files to test themselves against. [browser-compat-data has robust schemas](https://github.com/mdn/browser-compat-data/tree/master/schemas) which could be referenced to write similar ones for caniuse-db.

> Do you see warnings from Browserslist?

There won’t be warnings for anyone who takes in the patch release, since the `all` version has been removed.

> Preset Env should not trust to Can I Use feature JSONs

1. I agree. I failed to fathom caniuse-lite producing results incompatible with browserslist, and now I see how flawed that assumption was. From the moment I enter into the `stats` object, I will not trust any object to be shaped as I had presumed.
2.  I have been sluggish to develop a good pattern for plugins to provide their own id mappings to caniuse or browser-compat-data. This is becoming more necessary as features are unevenly implemented in browsers.

> be ready for non-existed browsers

If caniuse feeds me imaginary browsers or imaginary browser versions, how would I know those browsers or versions are not supported by browserslist? That seems like an issue to be resolved in browserslist.

I am sorry I have not been able to help more on the browserslist project. I spent significant time trying to understand how browser queries were generated there, but I was unable.

**Comment by ai** [comment]
> If caniuse feeds me imaginary browsers or imaginary browser versions, how would I know those browsers or versions are not supported by browserslist?

`ignoreUnknownVersions` should help.

Or maybe we should add `ignoreUnknownQuery` to be sure?

> I am sorry I have not been able to help more on the browserslist project.

Don't worry. You don't need to be deep in Browserslist, it is my responsibility to help everyone to use it.

**Comment by ai** [comment]
I thought about `ignoreUnknownQuery` and found that it is not the best way. We need to find that Can I Use data is broken.

What if `BrowserslistError` will contain broken query and you will drop it from the list and show warning?

```js
function query (browsers) {
  try {
    return browserslist(browsers, opts)
  } catch (e) {
    if (e.name === 'BrowserslistError' && e.brokenQuery) {
      console.warn('Can I Use data contains unknown browser ' + e.brokenQuery)
      return query(browsers.filter(i => i !== e.brokenQuery))
    } else {
      throw e
    }
  }
}
```

**Comment by jonathantneal** [comment]
That would work for me. For now, I am closing this issue as it was unrelated to this project.
