### ISSUE TITLE
Update Browser Compatibility Stategy

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#138]
- [ ] **Stat parsing should handle unexpected changes to the shape of stat objects.**
   Recently, caniuse-db innocently changed something extremely minor about the shape of their stats object that temporarily broke a lot of projects. All of these polyfills rely on correctly parsing stats.

- [ ] **Plugins should expose their own stat ids.**
   It is becoming difficult to manage 1. a couple dozen CSS polyfills and their configuration, 2. the polyfill plugin pack that combines, sorts, and individually configures all of them, 3. the cssdb map of progress/status of CSS specifications and implementations, and 4. the implementation of matching a browserslist to the status of a feature to a CSS polyfill.

**Comment by jonathantneal** [comment]
@ai, I am thinking of solutions, but if you have a moment for feedback, I would be very interested in your thoughts on the **stat id** issue.

**Comment by jonathantneal** [comment]
### Plugin Configuration (Take 2)

Allow plugins to deeply control their own default options.

- A short-hand example without documentation:

```js
Object.assign(
  postcss.plugin(...plugin),
  {
    config: {
      if: {
        stats: [
          { mdn: 'custom-property' },
          { caniuse: 'css-variables' }
        ]
      },
      then: {
        opts: { transform: false }
      }
    }
  }
)
```

- A long-hand example without documentation:

```js
Object.assign(
  postcss.plugin(...plugin),
  {
    config: [
      {
        if: [
          {
            stats: [
              { mdn: 'custom-property' },
              { caniuse: 'css-variables' }
            ],
            user: [
              {}
            ]
          }
        ],
        then: {
          opts: { transform: false }
        }
      }
    ]
  }
)
```

A long-hand example with documentation:

```js
Object.assign(
  postcss.plugin(...plugin),
  {
    // "config": which is;
    // 1. an array of configuration objects, where;
    //    * the first matching configuration is used; or,
    // 2. a single configuration object that must match to be used by the plugin; or,
    // 3. an omitted property or empty value that will be ignored; and
    config: [
      // configuration: an object of conditions and a corresponding configuration, where;
      // * "if": is the condition or conditions that must match to enable the configuration; and,
      // * "then": is the configuration that will be used by the plugin when enabled
      {
        // "if": which is;
        // 1. an array of condition objects, where;
        //    * the first matching condition enables the configuration; or,
        // 2. a single condition object that must match to enable the configuration; or,
        // 3. an omitted property or empty value that will enable the configuration
        if: [
          // condition: an object of terms, like "stat" or "user", where;
          // * all terms of a condition must match to enable the configuration
          {
            // "stat": which is;
            // 1. an array of statistic key-values, where;
            //    * the first matching statistic key-value will pass the term; or,
            // 2. a single statistic key-value that must match to pass the term; or,
            // 3. an omitted property or empty value that will pass the term
            stats: [
              // statistic: a key-value pair, where;
              // * the key is the statistic service, like "caniuse" or "mdn"; and,
              // * the value is the feature id, like "custom-property" or "css-variables"
              { mdn: 'custom-property' },
              { caniuse: 'css-variables' }
            ],
            // "user": which is;
            // 1. an array of options objects; where,
            //    * the first matching options object will pass the term; or,
            // 2. a single options object that must match to pass the term; or,
            // 3. an omitted property that will pass the term; or,
            // 4. an empty value that will not pass the term
            user: [
              // options: the options passed to the plugin by the user, where;
              // * the options are always coerced into an object
              {}
            ]
          }
        ],
        // "then": the configuration used by the plugin when enabled
        then: {
          // "opts": the options object passed to the plugin, where;
          // * options passed to the plugin by the user still take precedent
          opts: { transform: false }
        }
      }
    ]
  }
)
```

##### Notes

- Very extendable, but potentially verbose for simple configurations (see short-hand example).
- Require options to be coerced into an object.
- User options still take precedent over generated options.

**Comment by jonathantneal** [comment]
There’s a fatal flaw in the above proposal that make it not work for plugins like PostCSS Logical.

I need the ability to individually configure multiple properties within options. Here is the scenario I need to account for:

**If** some mdn-defined feature is supported by the project browserlists **then** toggle some corresponding property in the plugin options. Then, **if** some other mdn-defined feature is supported by the project browserslist **then** configure another corresponding property in the plugin options.

**Comment by ai** [comment]
Oops. I missed the mention.

I can’t comment internal refactoring because I did not work with the code.

I found the config proposal, but can you show current and new strategy to compare?

**Comment by jonathantneal** [comment]
I’m still working it out. These delays are starting to reach an epic proportion. I’m so sorry.

**Comment by simontaisne** [comment]
Hi @jonathantneal, related to your [comment](https://github.com/csstools/postcss-logical/issues/16#issuecomment-499566147) on `PostCSS Logical`.

Since caniuse data leads to false positives and because there is currently no way to enable/disable specific logical transforms, what would you think of defaulting to a "always transform" strategy?

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
