### ISSUE TITLE
Specific nesting rules do not work

### ISSUE THREAD

**Issue by Galy4a** [csstools/postcss-preset-env#142]
Work:
```
<div class="a">
  <div class="b"></div>
</div>

.a {
& .b {...}
}
```

Don't work:
```
<div class="a">
  <div class="a-b"></div>
</div>

.a {
&-b {...}
}
```

**Comment by jonathantneal** [comment]
`&-b` does not work. While that might work in Sass, the CSS Nesting specification makes the `&` nesting selector a unique reference, as though it were wrapped in `:is()`.

In CSS, that means `&-b` is read more like `:is(&)-b`.
