### ISSUE TITLE
font-family name with color gets changed to hex

### ISSUE THREAD

**Issue by SnooHD** [csstools/postcss-preset-env#143]
Hello,
I am using nuxt, which uses this preset by default.

When i use a font-family name that contains a color like:
`font-family: 'Black Han Sans';` it gets changed to `font-family: '#000 Han Sans';`

Is there an easy way to prevent this from happening?

A repro can be found here:
https://codesandbox.io/s/black-han-sans-repro-fieb8

The generated build can be found in `dist/index.html`

**Comment by jonathantneal** [comment]
That sounds like an issue with a CSS minifier, and not with the plugins inside this project. I looked at your CodeSandbox and did not see an option to disable postcss-preset-env. Disabling that plugin specifically would help us see whether it was an issue with this project, or another css tool that you are using. Would you know how?

**Comment by GrimLink** [comment]
@SnooHD can you check which CSS minifier is used?

This is not a Postcss-preset-env issue @jonathantneal 

I have the same issue with CSSNano.
And so disabled the color minification rule. 

```js
{
  preset: ['default', { colormin: false }]
}
```

**Comment by Semigradsky** [comment]
> A repro can be found here:

@SnooHD looks like defect not reproduced more

**Comment by SnooHD** [comment]
@Semigradsky yes you are correct, this is no longer an issue :)
