### ISSUE TITLE
`importFrom` with `preserve: true` does not produce global `:root` tag with all the imported custom properties

### ISSUE THREAD

**Issue by mifrej** [csstools/postcss-preset-env#149]
Hello
I'm trying to setup a project where my custom properties live in one global file imported by `importFrom` option. But I don't see generated file with them being grouped all in `:root { /* all imported vars here */}`. So in other words. They are imported and poly-filled to regular hex values, but native implementation e.g. (`color: var(--primary);`) does not have source available in the browser runtime.

Hope this example boilerplate with commit will picture it better
https://github.com/mifrej/next-js-with-postcss-preset-env

With `preserve: false` all works but thus I lose the native implementation of custom properties in the browser.

My expectation is that I will get the properties generated by webpack in shape `:root { /* all imported vars here */}`

**Comment by TommySorensen** [comment]
I have the same problem as you described. I'm using `importFrom` to get some colors from a node_modules folder. It only works if i set `preserve: false`.

**Comment by moonray** [comment]
Same problem here.

**Comment by thehappycoder** [comment]
I've got this too.

**Comment by mikestopcontinues** [comment]
Ditto. Any solutions?

It seems that the subpackages don't preserve imports. They should, but in either case, preset-env should supply some way of doing this.

Here's a ticket I opened at custom-properties:
https://github.com/postcss/postcss-custom-properties/issues/219

**Comment by mikestopcontinues** [comment]
I've been thinking, something like `@import-custom-properties` (etc) would be excellent, as it would help prevent duplicating the code block at every entry (unless needed).

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
