### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by tkrotoff** [csstools/postcss-preset-env#150]

**Comment by jonathantneal** [comment]
You’ll have to be more descriptive. Feel free to edit your empty description and I’ll consider reopening the issue.

**Comment by tkrotoff** [comment]
@jonathantneal description edited

**Comment by hgl** [comment]
@jonathantneal Currently if a typescript project tries to import `
postcss-preset-env`, `tsc` would complain:

```
Could not find a declaration file for module 'postcss-preset-env'. 
```

@tkrotoff's definition file solves it. Do you think it can be added to the repo or published as `@types/postcss-preset-env`

**Comment by tkrotoff** [comment]
There is now a @types/postcss-preset-env npm package: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7e8140cefa784d4f2865948d3bdf59da8189cd2/types/postcss-preset-env/index.d.ts
