### ISSUE TITLE
Document all feature names and warn on unrecognized features

### ISSUE THREAD

**Issue by ghost** [csstools/postcss-preset-env#156]
Hey there, just wasted a good chunk of the day trying to debug why custom media queries weren't being transpiled. It turns out I was trying to use the feature `custom-media` in my config, when in fact the feature is named `custom-media-queries`.

That might sound like a foolish mistake... except the name of the feature is simply not documented anywhere that I can tell:

- It's not in README.md or any other documentation in the repo
- If I check https://preset-env.cssdb.org/features#custom-media-queries, I can see that the feature _exists_, but not how to activate it:

  ![image](https://user-images.githubusercontent.com/56890998/70276570-9b79f280-177e-11ea-9715-6074bf9ef35a.png)

  (If I hit the "plugin" link above, the [plugin](https://github.com/postcss/postcss-custom-media) that preset-env wraps is in fact named "postcss-custom-media" -- not "postcss-custom-media-queries"! -- misleading me further.)

postcss-preset-env also happily accepts non-existent feature names in its config without raising a warning, which exacerbates the issue. If it had refused to run or raised a warning when I tried to activate the nonexistent `custom-media` feature, that would've at least saved me some debugging time!

**Comment by skrhlm** [comment]
Thank you **so** much for creating this issue. This saved my day.

I was going crazy over why custom media queries was being skipped. This helped me figure out that it actually ( seems very clear now in retrospect ) does not polyfill them since it's only in stage 1 and the default for `postcss-preset-env` is `{stage:  2}`.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
