### ISSUE TITLE
Trouble getting global nested block to work

### ISSUE THREAD

**Issue by jnrepo** [csstools/postcss-preset-env#157]
Hi, I'm trying to get something like this to build

```
:global {
  select {
    padding-right: 20px;
  }
}
```

Tried these options:
```
postcssPresetEnv({
        stage: 1,
        features: {
          'nesting-rules': true
        }
      })
```
```
postcssPresetEnv({
        stage: 3,
        features: {
          'nesting-rules': true
        }
      })
```

Also tried to add the `&` prefix, yet that didn't work either. 
```
:global {
  & select {
    padding-right: 20px;
  }
}
```

What's the correct way to nest with global block scopes?

**Comment by Semigradsky** [comment]
@jnrepo `:global` is [`css-modules`](https://github.com/css-modules/css-modules) feature.
What do you expect from `postcss-preset-env`?
