### ISSUE TITLE
Element scoped css variables

### ISSUE THREAD

**Issue by coolemur** [csstools/postcss-preset-env#159]
Hello,

I'm having an issue with custom-properties used with nesting rules.

My gulp config so far:

```
...
      .pipe(postcss([
        postcssImport(), 
        postcssPresetEnv({
          /* use stage 3 features + css nesting rules */
          stage: 0,
          features: {
            "nesting-rules": true,
            "custom-media": true,
            "custom-properties": true,
            "custom-selectors": true,
          },
          importFrom: [`settings.css`]
        }),

        postcssFontpath(
          {
            formats: [
              { type: 'woff2', ext: 'woff2' },
              { type: 'woff', ext: 'woff' },
              { type: 'truetype', ext: 'ttf' }
            ]
          }
        ),
       
      ]))
      .pipe(concat("app.css"))
...
```

I expect custom properties to work locally like so (element scoped css variables is supported in modern css):
```
.foo {
  --custom-padding: 15px;

  & .bar {
    padding: var(--custom-padding);
  }
}
```

This only works when I move variable declaration into settings file into :root () where variables are imported to css (importFrom).

Is this a missing feature or I'm missing something in configuration ?

**Comment by elgandoz** [comment]
I have the same issue... how did you solve it?

**Comment by coolemur** [comment]
> I have the same issue... how did you solve it?

@elgandoz I don't use postcss anymore. And in scss element scoped variables work.
