### ISSUE TITLE
Update Browserslist, caniuse-lite outdated

### ISSUE THREAD

**Issue by Nettsentrisk** [csstools/postcss-preset-env#161]
I'm getting this error in my build which seems due to outdated version of Browserslist or caniuse-lite: 

> Browserslist: caniuse-lite is outdated. Please run next command `npm update`

**Comment by Semigradsky** [comment]
So what about run `npm update`?

**Comment by Nettsentrisk** [comment]
Doesn't help, caniuse-lite stays at 1.0.30000989 regardless, have tried npm update and npm update --depth 99 etc.
