### ISSUE TITLE
[Plugin request] rgb/hsl -> rgba/hsla

### ISSUE THREAD

**Issue by Semigradsky** [csstools/postcss-preset-env#162]
https://www.w3.org/TR/css-color-4/

rgb() & hsl() now accept a 4th parameter.
So need to have plugin for converting `rgb`/`hsl` functions to legacy `rgba`/`hsla`

---
caniuse issue: https://github.com/Fyrd/caniuse/issues/4732

**Comment by Serator** [comment]
https://preset-env.cssdb.org/features#color-functional-notation

**Comment by Semigradsky** [comment]
This ticket is not about color functional notation.

**Comment by Semigradsky** [comment]
> For legacy reasons, rgb() also supports an alternate syntax that separates all of its arguments with commas:
>
> ```
> rgb() = rgb( <percentage>#{3} , <alpha-value>? ) |
>         rgb( <number>#{3} , <alpha-value>? )
> ```

So need to convert `rgb(70%, 13.5%, 13.5%, 50%)` to `rgba`

**Comment by argyleink** [comment]
if that was my goal, i'd still use [postcss-color-functional-notation](https://github.com/csstools/postcss-color-functional-notation)
