### ISSUE TITLE
"preserve" option on playground

### ISSUE THREAD

**Issue by privatenumber** [csstools/postcss-preset-env#171]
Can the [Codepen preset-env playground](https://csstools.github.io/postcss-preset-env/) also have the "preserve" option?

Was demonstrating the difference it makes to a colleague and wished it was available there.

Happy to open a PR but couldn't find the repo for it.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
