### ISSUE TITLE
Nesting not being applied at any stage setting

### ISSUE THREAD

**Issue by spacedawwwg** [csstools/postcss-preset-env#177]
I have tried stage `0,1,2,3,4` and none apply the 'nesting' rules.

I have also tried using `features: { 'nesting-rules': true' }` with no success.

my `postcss.config.js` is:

```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-pxtorem')({
      propWhiteList: [],
    }),
    require('postcss-preset-env')({
      autoprefixer: {
        grid: true,
      },
      preserve: false,
      stage: 1,
    }),
    require('postcss-remove-root'),
  ],
};
```
Is there something I'm missing?

**Comment by jonathantneal** [comment]
Without having any CSS code to look at, my best guess is that you are not using CSS Nesting.

**This is CSS Nesting**:

```pcss
.component {
  & input {}
}
```

**This is _not_ CSS Nesting**:

```pcss
.component {
  input {}
}
```

If one is coming from Sass, this is a common thing to get tripped up on.

Does that help?

**Comment by spacedawwwg** [comment]
@jonathantneal It does. That was 100% it! Thanks. I think I need to fall back to `postcss-nested` (https://github.com/postcss/postcss-nested) for now and think about refactoring my CSS to be more future proof

**Comment by ajayjaggi97** [comment]
hey @spacedawwwg .
I have @nest directive which is not getting converted to vanilla css.
