### ISSUE TITLE
Features documentation Stage versions out of date?

### ISSUE THREAD

**Issue by chrishrtmn** [csstools/postcss-preset-env#182]
Hello! Viewing the Features page (https://preset-env.cssdb.org/features) and then clicking/reading up on the Specifications links of the features shows discrepancies on Stages. 

Eg: https://preset-env.cssdb.org/features#prefers-color-scheme-query Shows as Stage 1 but is in Stage 5 (to my understanding) https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

Not sure if I'm just confused or if the website just needs to updated?

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
