### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by doasync** [csstools/postcss-preset-env#188]
Please, add types for `postcss-preset-env`

---

The following import in a `.ts` file:
```
import presetEnv from 'postcss-preset-env';
```
gives the following error:
```
TS7016: Could not find a declaration file for module 'postcss-preset-env'. '/Users/doasync/Projects/stellardex/node_modules/postcss-preset-env/index.js' implicitly has an 'any' type.   Try `npm install @types/postcss-preset-env` if it exists or add a new declaration (.d.ts) file containing `declare module 'postcss-preset-env';`
```

**Comment by romainmenke** [comment]
`postcss-preset-env` has been moved to https://github.com/csstools/postcss-plugins
We have a setup to write the actual plugins in typescript and we will try to port `postcss-preset-env`.

Personally not a fan of adding `.d.ts` files as these quickly become outdated and incorrect.
Better to have actual typescript.
