### ISSUE TITLE
Conflict with postcss-import plugin?

### ISSUE THREAD

**Issue by onetrev** [csstools/postcss-preset-env#199]
In my webpack config `postcss-preset-env` seemingly does nothing when I have `postcss-import` included. As soon as postcss-import is removed everything works as usual (my CSS is prefixed, media range queries converted, etc.). But no errors are emitted so not sure what the problem is. 

```
{ 
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    postcssOptions: {
      plugins: [
        [
          "postcss-import",
          "postcss-preset-env"
        ],
      ],
    },
  }
},
```

**Comment by nucliweb** [comment]
You have a syntax error.

The correct way is:
```js
{ 
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    postcssOptions: {
      plugins: [
        ["postcss-import" ],
        ["postcss-preset-env"],
      ],
    },
  }
},
```

And if you want to add options to the plugins:

```js
{ 
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    postcssOptions: {
      plugins: [
        ["postcss-import" ],
        [
         "postcss-preset-env",
         {
           // Plugin options
         }
        ],
      ],
    },
  }
},
```

**Comment by onetrev** [comment]
Awesome, thanks @nucliweb. I had tried a ton of things first, but of course I missed the obvious and much simpler explanation just a classic syntax error. I think I missed trying that because when scanning through the Webpack docs and their example of postcss-loader with [multiple plugins](https://webpack.js.org/loaders/postcss-loader/#object) `postcss-import` wasn't contained within square brackets. Thanks again!
