### ISSUE TITLE
High Severity security issue introduced via lodash.template (via postcss-initial)

### ISSUE THREAD

**Issue by c-frater** [csstools/postcss-preset-env#203]
https://snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

`lodash.template` is deprecated - Please swap to use `lodash` and import `template` from that

This is causing issues in many of our production applications so would appreciate a swift resolution

```
postcss-preset-env@6.7.0
  └─┬ postcss-initial@3.0.2
    └── lodash.template@4.5.0 
```

Cross-posted for visibility: https://github.com/maximkoretskiy/postcss-initial/issues/44

**Comment by romainmenke** [comment]
This has been resolved in the latest versions and we now use dependabot to better keep up with dependencies.

This repo has also been moved to https://github.com/csstools/postcss-plugins
