### ISSUE TITLE
can't find browserslist config in a webpack multi-config build

### ISSUE THREAD

**Issue by dreyks** [csstools/postcss-preset-env#204]
I have a webpack config that builds several others configs exporting them as an array

This is a simplified setup (with only one subapp)

```
.
├── subapp
│   ├── babel.config.js
│   ├── postcss.config.js
│   └── webpack.config.js
└── webpack.config.js
```

See how there's no other config files in the root dir. the only webpack's job here is to orchestrate other builds which in turn use their own babel and postcss configs

```js
// root webpack.config.js

import subApp from './subapp/webpack.config.js'

export default [
  subApp
]
```

```js
// subapp postcss.config.js

module.exports = () => ({
  plugins: [
    require('postcss-preset-env')({
      // postcss-preset-env config
    })
  ]
})
```

So the issue is that when postcss-preset-env asks browserslist for a list of browsers it doesn't pass any path option so browserslist defaults to `path.resolve('.')` which is the root folder. But the root folder doesn't have any browserslist config so a default browser set is returned

Am I doing weird things and this use-case is not supported?) Or is it possible to make a change so that postcss-preset-env passes its own location as path for browserslist?

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
