### ISSUE TITLE
FR: support for choosing browserslists environments

### ISSUE THREAD

**Issue by masi** [csstools/postcss-preset-env#206]
The browserslist may consist of any number keys naming "environments". They can be used for different builds:

https://github.com/browserslist/browserslist#configuring-for-different-environments

In other tools, eg Babeljs, I can choose which environment to use.

https://babeljs.io/docs/en/babel-preset-env#browserslistenv

If BROWSERSLIST_ENV is already suppoerted, please update the docs.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
