### ISSUE TITLE
`lch()` not working

### ISSUE THREAD

**Issue by vjee** [csstools/postcss-preset-env#208]
When setting `stage` to `2` as to be able to use `lch()`, it's not being transformed.
Neither when setting `lab-function` (same plugin) to `true` in `features`.

When manually using `postcss-lab-function` however, it works as expected.

**Comment by andparsons** [comment]
I'm having the same issue. It looks like when used via `postcss-preset-env` the `lab/lch` function isn't able to parse the first param as a percentage, and only works in the older format without.

**Comment by romainmenke** [comment]
@vjee Is this still an issue with the latest versions?
If so can you provide an example input?

**Comment by vjee** [comment]
@romainmenke It seems to work just fine now!
Here's an example: https://runkit.com/embed/kfsp7ev1rmr9
Thanks for checking this issue out. It can be closed as far as I'm concerned :)
