### ISSUE TITLE
Fix npm vulnerabilities from postcss

### ISSUE THREAD

**Issue by SergKozyrev** [csstools/postcss-preset-env#209]
> What

 is the problem you're trying to solve?

I want to fix npm vulnerabilities from postcss.

> What solution would you like to see?

"dependencies": {
    ...
    "postcss": "^8.2.15",
    ...
}

**Comment by romainmenke** [comment]
This has been resolved in the latest versions and we now use dependabot to better keep up with dependencies.

This repo has also been moved to https://github.com/csstools/postcss-plugins
