### ISSUE TITLE
Include Autoprefixer

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#21]
The creator of PostCSS and Autoprefixer thinks Autoprefixer should be included in postcss-preset-env.

https://github.com/MoOx/postcss-cssnext/issues/445#issuecomment-384059823

**Comment by SterlingVix** [comment]
Considering that `postcss-preset-env` is intended to be a group of sane, default plugins for PostCSS, I agree that `Autoprefixer` seems like a requirement.
