### ISSUE TITLE
Can this package be installed as a devdependency?

### ISSUE THREAD

**Issue by JessNah** [csstools/postcss-preset-env#216]
Hi! I wanted to know if postcss-preset-env can be used as a dev-dependency or if it has to be a dependency because I guess it is used as runtime? or is it compile time?

Thank you!

**Comment by jsg2021** [comment]
it's a dev dependency for me.

**Comment by lumburr** [comment]
`postcss-preset-env` supports you to use future css syntax during development. The future css syntax will be compiled into current css syntax by `postcss-preset-env` during development. At this time, it is your development dependency. The future css syntax cannot make the project run in the production environment. When the project is packaged, `postcss-preset-env` will downgrade the future css syntax to the current css syntax. At this time, the project can run normally without `postcss-preset-env`. It is also compiled, it is not a project dependency.
