### ISSUE TITLE
Complex nesting transpiling with using :is pseudo selector and breaks compat with old browsers

### ISSUE THREAD

**Issue by igorushko** [csstools/postcss-preset-env#234]
Plugin [postcss-nesting](https://github.com/csstools/postcss-nesting), begins from 8 version, transpiling complex nesting with using **:is** pseudo selector. In fact, this is not a plugin bug, since not specified browser compat. But postcss-preset-env specified compat with all browsers.

Reproduse:
```js
import postcss from "postcss";
import postcssPresetEnv from "postcss-preset-env";

const res = await postcss([
	postcssPresetEnv({
		features: {
			'nesting-rules': true
		},
  	})
]).process(`
.a, .b {
	&:before {
		content: "";
	}
}`);

console.log(res.css);
```

Output:
```css
:is(.a,.b):before {
	content: "";
}
```

I'm was trying to adds [postcss-pseudo-is](https://github.com/IlyaUpyackovich/postcss-pseudo-is), but it's plugin not support nesting **:is** selectors and it's not work in case like this:
```css
.a, .b {
  &.c,&.d {
    &:before {
      content: "";
    }
  }
}
```

Ways to fix:
1. Remove using **:is** from [postcss-nesting](https://github.com/csstools/postcss-nesting) (easy way)
2. Modify [postcss-pseudo-is](https://github.com/IlyaUpyackovich/postcss-pseudo-is), for supports nesting selectors and resolve other plugin limitations.

@jonathantneal @Antonio-Laguna what do you think about it?

Workaround:
I disabled nesting in postcss-preset-env and use [postcss-nested](https://github.com/postcss/postcss-nested)

I'm using
"postcss": "^8.4.5"
"postcss-preset-env": "^7.0.1"

**Comment by Antonio-Laguna** [comment]
@igorushko thanks for taking the time to write this and elaborate this much!

That said, what you're reporting makes complete sense to me. The spec went through a [revision](https://drafts.csswg.org/css-nesting-1/) lately and it does mention `:is` within it and in the process of following it to the letter we forgot about older browsers.

We can improve this and hopefully shouldn't be a major effort. We'll keep you updated!

**Comment by romainmenke** [comment]
@igorushko Again, thank you for opening this issue :)

I think I am about half way through rewriting the current algorithm to something that is more aware about how selectors actually work.

This removes most (but not all) cases where `:is()` is used as glue in selectors.
You can follow along here : https://github.com/csstools/postcss-plugins/pull/72

**Comment by romainmenke** [comment]
@igorushko We have just published a new release with improvements for this.

`postcss-nesting` now tries to avoid `:is()` as much as allowed by the spec.
There is also the option to disable `:is()` completely :

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting#noispseudoselector

```js
postcssNesting({
	noIsPseudoSelector: true
})
```

--------

`postcss-preset-env` looks at the browsers list provided and sets this flag for you when needed.
If you do not use a browsers list you can set it manually :

```js
stage: 0,
features: {
	'nesting-rules': {
		noIsPseudoSelector: true
	}
}
```

--------

Can you let us know if this fully resolves your issue?

**Comment by igorushko** [comment]
I tested this on my codebase, it looks good!

I think this issue has been resolved, thanks for the great work!

Like proposal: i think you can determinate use **:is** or not, based on browsers option. This would be the style of the "env" plugin :)
