### ISSUE TITLE
Clarify relationship between browsers option and stage and features options

### ISSUE THREAD

**Issue by galvarez421** [csstools/postcss-preset-env#24]
I think it would be helpful to update the README to clarify the relationship between the `browsers` option and the `stage` and `features` options in the manner that the relationship between the `stage` and `features` options is described. For example, suppose I am using the [`all` property](https://cssdb.org/#all-property), a stage 3 feature supported as of Firefox 27. Suppose I set `stage` to `4` and `browsers` to `Firefox > 20`. Should I expect the feature to be polyfilled? (the `stage` option suggests no, while the `browsers` option suggests yes)

Very promising looking project by the way! I am currently working on migrating some projects from using postcss-cssnext to using this instead.

**Comment by Nemo64** [comment]
I jump a head and explain it as I understand it.
Stage defines the level of standardisation. A Stage 3 Feature will be a Stage 3 Feature, even if every browser in your query supports it (with polyfill or not).
And with `features` you can simply define that you need a feature, even though it doesn't match with your `stage`.

**Comment by jonathantneal** [comment]
@galvarez421, it works as @Nemo64 explained.

The `stage` option determines which features are polyfilled. The stage numbers represent the stability of a given feature, where a higher numbered feature is more stable. This is how babel-preset-env works.

Your [browserslist configuration](https://github.com/browserslist/browserslist#readme) determines whether those polyfills need be applied. This is also how babel-preset-env works. For instance, if your browserslist configuration supported everything babel otherwise compiled, then your source and compiled files would be identical.

For the majority of developers, we don’t want them thinking about using the `browsers` option, because using one, universal browserslist configuration means postcss and babel share the same preferences.

Okay, even further down the road of advanced usage is `features`. By using this feature, one is disregarding the staging process, their browserslist configuration, caniuse, etc. and deciding they know better.

**Comment by galvarez421** [comment]
Thank you for the prompt reply, although I am still not sure I understand 100%!

> The stage option determines which features are polyfilled.

> Your browserslist configuration determines whether those polyfills need be applied.

Isn't it fair to say that these options are different ways of specifying which polyfills you want to apply?

> For the majority of developers, we don’t want them thinking about using the browsers option, because using one, universal browserslist configuration means postcss and babel share the same preferences.

I am planning to use a single Browserslist config to use with both postcss-preset-env and babel-preset-env along with any other tools that implement Browserslist. In my OP, I wasn't interested in the `browers` option per se but rather, more directly, in the interaction between the Browserslist query being used (whether it's via the `browsers` option or a Browserslist config file) and the other postcss-preset-env options.

> Okay, even further down the road of advanced usage is features. By using this option, one is disregarding the staging process, their browserslist configuration, caniuse, etc. and deciding they know better.

This is primarily what I am confused about, i.e., the relationship between these options. The documentation suggests that `stage` and `features` will essentially be merged, so I am wondering if the `browsers` option is likewise merged. To be precise, is the behavior to apply polyfills necessary to satisfy `stage` AND to satisfy `features` AND to satisfy `browsers` where, in the case that the options contradict one another (see example in OP), the polyfill is applied if applying it would satisfy ANY of the options?

**Comment by jonathantneal** [comment]
@galvarez421, I completely agree that the documentation could be better.

I’ve updated the documentation [just now](https://github.com/csstools/postcss-preset-env/commit/f1d076e858267ef8d1eeecb0c7a053276194942e), based on your feedback.

Would you checkout the options section and tell me if it’s easier to read now? https://github.com/csstools/postcss-preset-env#options

**Comment by Nemo64** [comment]
@jonathantneal all links to cssdb.org are now gone.

**Comment by jonathantneal** [comment]
You can’t access https://cssdb.org/ ?

**Comment by Nemo64** [comment]
No I mean: all links in the read me are gone.

**Comment by galvarez421** [comment]
@jonathantneal Thank you for updating the documentation. I think the changes help make things a bit clearer.

One thing I'm still wondering about specifically. Given the following example:

styles.css:

```
* {
  all: initial;
}
```

postcss-preset-env config:

```
{
  stage: 4,
  features: {
    'all-property': false
  },
  browsers: '> Firefox 25'
}
```

Given that `all` is a Stage 3 feature supported as of Firefox 27, according to https://cssdb.org/#all-property, should I expect the `all` property to be polyfilled?

Side note: I think the documentation regarding the `features` option could still be improved. The text seems to suggest each feature id should be a property in an object (as in the code sample above) or should contain an object, while the code example shows an array with a feature id string.

**Comment by Nemo64** [comment]
Nope, if you say you only want to use stage 4 features, you'll only get stage 4 features.
If you want everything thats possible use stage 0.

The reason you might not want to use such a low stage is that the features in stage 0/1/2 might still change in the future. So with the stage option you basically define how adventures you are and how willing you are to fix stuff if it changes/breaks.

Also you'll probably have a little faster builds if you don't include 30 polyfills for features you might not even be using.

**Comment by galvarez421** [comment]
OK I see now! I think @jonathantneal pretty much explained that in his first comment but I guess it just didn't click with me:

> The stage option determines which features are polyfilled... Your browserslist configuration determines whether those polyfills need be applied.

So, the order of priority is:

`browsers (least priority) --> stage --> features`

One final suggestion for improving the documentation would be to specify the default values for each option.

**Comment by jonathantneal** [comment]
Resolved via https://github.com/csstools/postcss-preset-env/commit/5474462f8b01e3bd0f17f3bb184f6e11e85997f5#diff-04c6e90faac2675aa89e2176d2eec7d8
