### ISSUE TITLE
Some sort of list of what features are supported.

### ISSUE THREAD

**Issue by Nemo64** [csstools/postcss-preset-env#25]
I know that I can look into the `package.json` to get a good guess what features are polyfilled but that might not be too obvious.

Some kind of list would be useful? The badges from cssdb.org can probably be included for good measure. And also documentation that some further work is needed like with https://github.com/jonathantneal/postcss-focus-within ... which when I think about it isn't that great since the polyfill might fall out of the support list but the javascript is still included but that might be another issue.

Or another idea would be to include a command that simply lists what plugins are applied.

**Comment by dbox** [comment]
https://preset-env.cssdb.org/features

**Comment by Nemo64** [comment]
Very nice. Almost exactly what I want.

The only thing missing is notes which polyfills aren't complete and which polyfills require additional javascript.
Examples:

- custom properties only supports properties on `:root`
- `:focus-within` requires javascript for it's fallback

Those are the ones i'm aware of.

**Comment by dbox** [comment]
A little "note/alert" option would help for sure!

![image](https://user-images.githubusercontent.com/296130/40240153-8d895a0e-5a7d-11e8-8312-4fbe23ef74fd.png)

I didn't realize some needed additional JS... isn't that out of scope for this plugin?

**Comment by jonathantneal** [comment]
Thanks, @dbox, for answering this question. Also, we now have https://preset-env.cssdb.org/features to be extra clear.

**Comment by mdmoreau** [comment]
@jonathantneal Would it be possible to note which features require additional JS? Not sure how feasible it is, but it would also be great to have some sort of automatic browserslist-based JS import for any features that require additional scripts.
