### ISSUE TITLE
Adding postcss-flexbugs-fixes for fixing at least some flex bugs with IE 10-11

### ISSUE THREAD

**Issue by ChristianStornowski** [csstools/postcss-preset-env#27]
Is it possible to add this plugin https://github.com/luisrudge/postcss-flexbugs-fixes to solve some flex bugs?

This purpose is not only to fix IE 10 or 11 Bugs but also maybe some if these bugs: https://github.com/philipwalton/flexbugs

**Comment by jonathantneal** [comment]
I think these older issues should be captured in a plugin for preset-env — something specifically for legacy browsers.

**Comment by Nemo64** [comment]
I haven't used flex box enough to have an educated opinion on these fixes.
But it seems like that most of these fixes require additional knowledge about the problem so it isn't a "throw in and don't think about it" fix. Then again: if it doesn't break anything (which i don't know) then i'm all for it. The custom property polyfill doesn't implement all cases but is nice nonetheless.

**Comment by Lysholm** [comment]
ie11 is still, regrettably, so widely used that i don't think it warrants creating a legacy-plugin for fixes to it. But regarding this plugin specifically - it seems to cover a subset of bugs related to flex in ie11 and i fear that including it would do a disservice to a developer who wants to use flex in IE11. 

Set of flex features.
Set of flex features that work correctly in IE11
Set of flex features that work correctly in IE11 with this plugin.

These three are all dissimilar enough that i think this plugin needs to mature a little before it's included.
I'd be more inclined to use a plugin that issues a warning if any known bugged features are used when affected browsers are in the target browsers.

**Comment by jonathantneal** [comment]
If someone wants to make a PR for this, I will accept it.

**Comment by ChristianStornowski** [comment]
Maybe we could use https://www.npmjs.com/package/postcss-fixes in a PR.

**Comment by jonathantneal** [comment]
@ChristianStornowski, that would be possible, although unlikely.

PostCSS Fixes would need to include a browserslist. For instance, the double-colon `::` to single-colon `:` fix for ::before and ::after is only required for IE8. Same for unopacity and unroot.

As documented, only android 4.1 would want to get the nth-child fix.

Next, `postcss-calc` would have to go. It’s just an opinionated minifier that has a habit of slipping into standards-based libraries.

Finally, PostCSS Flexbugs Fixes would need to receive specific options to only fix the bugs impacting the browsers targeted by browserslist.

This would mean a pretty monumental change to postcss-fixes. It might be less monumental to attach caniuse-like data to each of the plugins and then include them in this package.
