### ISSUE TITLE
Options for postcss plugins

### ISSUE THREAD

**Issue by yepninja** [csstools/postcss-preset-env#29]
How to set up options for the postcss plugins?

**Comment by SammyM** [comment]
I'm not sure if this is the same thing, but I'd like to be able to pass the `variables` option to the `postcss-custom-properties` plugin (https://github.com/postcss/postcss-custom-properties#variables) so that I can access the variables from multiple different files. Is this possible?

**Comment by jonathantneal** [comment]
I will update or accept a PR to update https://github.com/csstools/postcss-preset-env#features to better demonstrate how one passes options into a plugin.

You pass options into a plugin using a `features.FEATURE_ID` option where `FEATURE_ID` is the feature you are targeting.

```js
{
  features: {
    'color-mod-function': {
      unresolved: 'warn'
    }
  }
}
```

We actively test this feature: https://github.com/csstools/postcss-preset-env/blob/master/.tape.js#L73-L77

**Comment by jonathantneal** [comment]
Updated in https://github.com/csstools/postcss-preset-env/commit/5474462f8b01e3bd0f17f3bb184f6e11e85997f5#diff-04c6e90faac2675aa89e2176d2eec7d8
