### ISSUE TITLE
A notice to cssnext users

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#32]
A third of a million weekly cssnext installs are about to get a deprecation notice redirecting them PostCSS Preset-Env, so let me explain what this project is, and what you need to know if you use cssnext.

### What is PostCSS Preset-Env

PostCSS Preset-Env is a bundle of CSS polyfills and prollyfills applied at compile time. It is like Babel Preset-Env for CSS. And like Babel, there are less stable and more stable features you can use, but only the safer features are polyfilled by default. Related: [The PostCSS Preset-Env homepage](https://preset-env.cssdb.org/).

### About features and changes

Disabling unstable features by default is an important departure from cssnext, and the change is to protect you and your team. This is because unstable features may change or disappear over time.

What should cssnext users do? They should take advantage of “stages”. Related: [The cssdb staging process](https://cssdb.org/#staging-process).

Like Babel, you can choose less stable or more stable features by specifying a “stage”. The stages are 0 - 4. The lower the stage number, the less stable the feature. Babel stages follow the [TC39](https://github.com/tc39/proposals) staging process, and PostCSS stages follow the [cssdb](https://cssdb.org/) staging process.

cssnext users have been using many “Stage 0” features, and so the smoothest transition for your team may be to [enable Stage 0 at first](https://github.com/csstools/postcss-preset-env#stage). Note: Nesting Rules are a Stage 0 feature.

Now, unlike Babel, PostCSS stages are not yet endorsed by or affiliated with a specification committee or browser vendor. If and when they are, that committee would likely be the [CSSWG](https://github.com/w3c/csswg-drafts). I am actively trying to establish a partnership with them. Related: [An issue to update cssdb with CSSWG feedback](https://github.com/csstools/cssdb/issues/31).

### About browser support

Both Babel and PostCSS support a “[browserslist](https://github.com/browserslist/browserslist)”, which is a sharable configuration that determines the browsers your project is supporting. Babel and PostCSS use this configuration to omit polyfills for features that your target browsers already support.

### About these projects

Babel and PostCSS were created to help developers accomplish real things with modern and emerging technologies. Both projects provide a great way for developers, authors, and implementors to communicate, thus improving the creation of standards, testing, feedback, and new use cases.

[You can try PostCSS Preset-Env in the browser right now](https://preset-env.cssdb.org/playground), and I hope you’ll consider using it in your next project. Thanks!

**Comment by Lysholm** [comment]
@jonathantneal: Babel looks to be dropping stage 0 - 2 when babel 7 releases (For reasoning see: https://github.com/babel/babel/issues/7770). I agree with their reasoning and think doing the same here would be a good idea (still include stage 0 - 2 features in preset-env but only expose them through the features option). What do you think? Doing that after release would probably annoy a great many people.

**Comment by jonathantneal** [comment]
@Lysholm, thanks for bringing that to my attention. I have certain disagreements with the suggestion in that issue, based upon [The Extensible Web Manifesto](https://extensiblewebmanifesto.org/), and [I’ve shared them back](https://github.com/babel/babel/issues/7770#issuecomment-392067055).

**Comment by Lysholm** [comment]
@jonathantneal: I see your point but i think we have different high level preferences. Regardless of available stages, suggesting that everyone opt in for stage: 0 seems to invite misuse. Maybe suggest stage: 2 + nesting? Not that users of cssnext aren't used to it, looking at `@apply`.

**Comment by pietrofxq** [comment]
@jonathantneal I have the current configuration of cssnext:

postcss.config.js
```
require('postcss-cssnext')({
      features: {
        customProperties: {
          variables: require('./src/css/variables')
        },
        customMedia: {
          extensions: require('./src/css/medias')
        }
      }
    })
```

I couldn't find a migration guide to help me move to postcss-preset-env since just replacing the module isn't working. What do I need to do to make this work with your module?

**Comment by pietrofxq** [comment]
@jonathantneal Thanks, the variables are being recognized now. However, looks like the original statement with the variable isn't being removed:

![image](https://user-images.githubusercontent.com/6238029/40859546-8a102a1a-65b8-11e8-8914-502e7e2e0946.png)

Do I need to implement something else to fix this? (I don't have this issue with cssnext)

**Comment by pascalduez** [comment]
@pietrofxq CSSnext was using an older versions of `postcss-custom-properties`, now the `preserve` option is set to `true` by default. Just set it to `false` in your config.

**Comment by HerrBertling** [comment]
My team found it rather hard to determine which stage to use – or whether it would be easier to stay with a certain stage and enable some features specifically.

So I ended up with a table of `postcss-cssnext` features, their `postcss-preset-env` counterparts (where I knew the option name) and the stage for each feature.

- `postcss-cssnext` features are from the [feature documentation page](http://cssnext.io/features/)
- Deprecation infos are [from the blogpost](https://moox.io/blog/deprecating-cssnext/) by @MoOx 
- Stages are from the `postcss-preset-env` [feature documentation page](https://preset-env.cssdb.org/features)
- Option names are from @jonathantneal's [comment](https://github.com/csstools/postcss-preset-env/issues/32#issuecomment-393754060)

Some parts are still left with a question mark, happy to add more info if someone can help :)

Here you go:

| cssnext feature                                 | preset-env option    | stage   
|-------------------------------------------------|-------------------------------------------|-------|
| automatic vendor prefixes ([link](http://cssnext.io/features/#automatic-vendor-prefixes)) | done via autoprefixer | / |
| custom properties & `var()` ([link](http://cssnext.io/features/#custom-properties-var)) | custom-properties | stage 3 |
| custom properties set & `@apply` ([link](http://cssnext.io/features/#custom-properties-set-apply)) | 🚫 | 🚫 ([removed](https://moox.io/blog/deprecating-cssnext/), [see here](https://www.xanthir.com/b4o00)) |
| reduced `calc()` ([link](http://cssnext.io/features/#reduced-calc)) | 🚫 | 🚫 ([removed](https://moox.io/blog/deprecating-cssnext/)) |
| custom media queries ([link](http://cssnext.io/features/#custom-media-queries)) | custom-media-queries | stage 1 |
| media queries ranges ([link](http://cssnext.io/features/#media-queries-ranges)) | media-query-ranges | stage 3 |
| custom selectors ([link](http://cssnext.io/features/#custom-selectors)) | custom-selectors | stage 1 |
| nesting ([link](http://cssnext.io/features/#nesting)) | nesting-rules | stage 0 |
| `image-set()` function ([link](http://cssnext.io/features/#image-set-function)) | image-set-function | stage 2 |
| `color()` function ([link](http://cssnext.io/features/#color-function)) | color-mod-function | stage 2 |
| `hwb()` function ([link](http://cssnext.io/features/#hwb-function)) | ? | stage 2 |
| `gray()` function ([link](http://cssnext.io/features/#gray-function)) | ? | stage 2 |
| `#rrggbbaa` colors ([link](http://cssnext.io/features/#rrggbbaa-colors)) | hexadecimal-alpha-notation | stage 2 |
| `rgba` function (`rgb` fallback) ([link](http://cssnext.io/features/#rgba-function-rgb-fallback)) | 🚫 | 🚫 ([removed](https://moox.io/blog/deprecating-cssnext/)) |
| `rebeccapurple` color ([link](http://cssnext.io/features/#rebeccapurple-color)) | ? | stage 2 💜 |
| `font-variant` property ([link](http://cssnext.io/features/#font-variant-property)) | ? | stage 3 |
| `filter` property ([link](http://cssnext.io/features/#filter-property)) | 🚫 | 🚫 (no info on that!?) |
| `initial` value ([link](http://cssnext.io/features/#initial-value)) | all-property | stage 3 |
| `rem` unit (`px` fallback) ([link](http://cssnext.io/features/#rem-unit-px-fallback)) | 🚫 | 🚫 ([removed](https://moox.io/blog/deprecating-cssnext/)) |
| `:any-link` pseudo-class ([link](http://cssnext.io/features/#any-link-pseudo-class)) | ? | stage 2 |
| `:matches` pseudo-class ([link](http://cssnext.io/features/#matches-pseudo-class)) | ? | stage 2 |
| `:not` pseudo-class ([link](http://cssnext.io/features/#not-pseudo-class)) | ? | stage 2 |
| `::` pseudo syntax (`:` fallback) ([link](http://cssnext.io/features/#pseudo-syntax-fallback)) | 🚫 | 🚫 ([removed](https://moox.io/blog/deprecating-cssnext/)) |
| `overflow-wrap` property (`word-wrap` fallback) ([link](http://cssnext.io/features/#overflow-wrap-property-word-wrap-fallback)) | overflow-wrap-property | stage 2 |
| attribute case insensitive ([link](http://cssnext.io/features/#attribute-case-insensitive)) | case-insensitive-attributes | stage 2 |
| `rgb()` function (functional-notation) ([link](http://cssnext.io/features/#rgb-function-functional-notation)) | ? | stage 1 |
| `hsl()` function (functional-notation) ([link](http://cssnext.io/features/#hsl-function-functional-notation)) | ? | stage 1 |
| `system-ui` font-family ([link](http://cssnext.io/features/#system-ui-font-family)) | system-ui | stage 2 |

I threw all of this into a gist to make it easier to fill in the blanks for others: https://gist.github.com/HerrBertling/fd69dcb5664eeb5543b761115d8b9ece

**Comment by jonathantneal** [comment]
Nice work, @HerrBertling. There are a lot of options, so I can see how this table you’ve created missed some from my original table.

rebeccapurple => rebeccapurple-color
font-variant => font-variant-property
:any-link  => any-link-pseudo-class
:matches => matches-pseudo-class
:not =>  not-pseudo-class

And for all color functional notation => color-functional-notation

Some of the other items that were removed were already being removed from cssnext because they were rejected specs, or targeted very old browsers, or were optimizations not really related to the future.

**Comment by HerrBertling** [comment]
Perfect, thanks :) Regarding the old, outdated features, I already thought so. Especially for the `filter()` one, changed the comment on that :)

**Comment by LockeAG** [comment]
just noticed that for postcss.config.js  , we should be call the plugin like 

        `'postcss-preset-env': {stage: 0,features: {'nesting-rules': true }},``


Right??

**Comment by killtheliterate** [comment]
Tried a few of the suggestions here, but cannot get `custom-properties` working with `preset-env`. It's copying the declaration that uses a variable, but not transforming the fallback. Was not able to get it working with the explicit `{features: { 'custom-properties': ...` either. In that example, what does the variable file look like?

Rollup config:
```javascript
{
    plugins: [
      postcssImport(),
      postcssUrl(urlOptions),
      postcssPresetEnv({
        stage: 0
      })
    ]
}
```

Input:
```css
.button {
  --button-border-color--base: #c4cacf;

  padding: 8px 12px;
  line-height: 1;
  border: 1px solid var(--button-border-color--base);

  background-color: transparent;
  border-radius: 3px;

  transition: all 0.3s ease 0s;
}
```

Output:
```css
.button {
  padding: 8px 12px;
  line-height: 1;
  border: 1px solid var(--button-border-color--base);
  border: 1px solid var(--button-border-color--base);

  background-color: transparent;
  border-radius: 3px;

  transition: all 0.3s ease 0s
}

```

**Comment by Amareis** [comment]
For brave souls - to reduce `calc` function as in cssnext you can use https://github.com/postcss/postcss-calc
Remember: you need to make `preserve: false` for custom properties plugin. Order of plugins matter, so in your `postcss.config.json` it will looks like 
```
    'postcss-custom-properties': {preserve: false},
    'postcss-preset-env': {stage: 0},
    'postcss-calc': {},
```

**Comment by pascalduez** [comment]
@killtheliterate You must declare your custom properties in a `:root` selector for the variable like behaviour and fallback to work, `postcss-custom-properties` can't fully reproduce the native behaviour without a DOM.

Also adding `postcss-reporter` at the end of your plugin list might help, since this kind of thing is reported as a warning.

**Comment by killtheliterate** [comment]
@pascalduez heya, thanks for the tip—I resolved the immediate issue by using `postcss-import` to `@import '../variables.css'`, which contains: 
```
:root {
  --foo: red;
}
```

This does lead to many duplicate declarations of `:root` in the output—is there a decent way to resolve this, maybe something that collapses them all down to the first one (so the cascade still works)?

**Comment by killtheliterate** [comment]
Found it -> https://github.com/postcss/postcss-custom-properties#variables

**Comment by spnc-omz** [comment]
Hi, thanks for this documentation, it's made transitioning a much smoother process. 

One outstanding question, is there a pre-existing plugin to transform color() to color-mod() or am I stuck writing my own until I can convert my source code to use color-mod?

**Comment by jonathantneal** [comment]
@spnc-omz, there is not an existing plugin to transform the pre-2015 `color` syntax into `color-mod`. I’ve wanted to devote some time to creating a plugin to analyze a css file and automatically update color methods, update range queries, and implement nesting, but I haven’t had the time, and don’t foresee having it very soon.

**Comment by spnc-omz** [comment]
@jonathantneal thanks for the response. While awaiting a response I wrote a quick plugin to inline within my config that would update those. We’re working through rewriting our source now to alleviate that need. I can share the source if anyone would find it beneficial.

**Comment by OezlemYi** [comment]
@jonathantneal I think the POSTCSS Preset Env option list campared with the nextcss options should be in the documentation. I searched 30 minutes how to set media queries option in stage 3 cause the option naming have changed and could be found nowhere else. In my opinion this is not an issue topic. This info should be globally accessible without searching.

**Comment by jonathantneal** [comment]
Folks can still reference this thread, but I will be closing it as an active issue.

**Comment by Dan9boi** [comment]
@jonathantneal how do you "require" (import) you custom-media and/or custom-properties (vars), like mentioned in https://github.com/csstools/postcss-preset-env/issues/32#issuecomment-393754060 when using `postcss.config.js`?

**Comment by jonathantneal** [comment]
I am working on that. It’s not a done feature and my time is limited. I’ve finished this work for Custom Selectors. I have a PR open for Custom Media. I have not started the work for Custom Properties.
