### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by danny-andrews-snap** [csstools/postcss-preset-env#33]
I've been waiting for a babel-esque solution for CSS features for quite a while now, and now it's here! Thank you!

p.s. It's a shame so many frontend folks have moved to solutions like styled-components and will not be able to enjoy all these spicy new CSS features. *sigh*

**Comment by jonathantneal** [comment]
Thanks for the kind words. I hope it helps a lot of people. I’m closing this after enjoying a month of free _good feels_. 😄
