### ISSUE TITLE
Add postcss-easing-gradients

### ISSUE THREAD

**Issue by ai** [csstools/postcss-preset-env#38]
Plugin: https://github.com/larsenwork/postcss-easing-gradients
Proposal: https://github.com/w3c/csswg-drafts/issues/1332
Description: https://larsenwork.com/easing-gradients/

Of course, it should be stage 0

**Comment by jonathantneal** [comment]
Until a spec exists **and** a CSSWG member or the CSSWG itself agrees to pick it up, I will not add this. Believe me — I’m watching this one closely — and I’m closing this issue regretfully.
