### ISSUE TITLE
Nesting with special char ?

### ISSUE THREAD

**Issue by dimic00** [csstools/postcss-preset-env#40]
Hey,

I recently migrate from cssnext to postcss-preset-env and got a problem with the nesting feature.

I am used to write my css like this : 

```
.myclass {
    &__children {
        &--childVariation {

        }
    }
}
```

Nesting is not working in this case. But if I write my css like this 

```
.myclass {
    &.nesting {

    }
}
```

It will work

Thank you !

**Comment by jonathantneal** [comment]
Unfortunately, that first kind of nesting (string appending) should never have worked with cssnext. In fact, that kind of nesting is now considered [a mistake in Sass](https://github.com/w3c/csswg-drafts/issues/2701#issuecomment-395572904).

I’m glad you’ve figured out how it is supposed to work, and I’m sorry you got used to a syntax that develops bad habits (see the link in the previous paragraph as to why).

**Comment by dimic00** [comment]
I read your argument and understand it but I'm not agree with you.
In my point of view it is not necessarily bad habit, it depend the way you use it (I approve you don't have to write it like it is HTML DOM).

Anyway, I will change my habit and waste time to write a lot of not necessary char for my BEM class ;)
