### ISSUE TITLE
Not transforming custom media queries

### ISSUE THREAD

**Issue by m-e-h** [csstools/postcss-preset-env#41]
Compiled CSS is leaving things like this `@media (--sm) {`
with this config:
```
"postcss": {
    "plugins": {
        "postcss-import": {},
        "postcss-simple-vars": {},
        "postcss-preset-env": {}
    }
}
```
If I add `postcss-custom-media` separately to the plugins, things work as expected.

`node v10.4.0`
`npm 6.1.0`

**updated
Actually hold on, I need test some things to see if I'm doing something incorrectly. There are several other included plugins not working...

**Comment by yepninja** [comment]
You don't configure stage option. The [default stage](https://github.com/csstools/postcss-preset-env#stage) is `2`. `Custom Media` feature is a part of `stage 1`. So it just needs to specify stage to 1.

**Comment by m-e-h** [comment]
Thanks @yepninja !! Exactly it.
Was just reading through the stage docs.
