### ISSUE TITLE
Some kind of attribute selectors is rewritten in a buggy way

### ISSUE THREAD

**Issue by a-t** [csstools/postcss-preset-env#44]
Hello!

I have a CSS rule like `div[data-title]:not([data-title=""]) { ... }` to style all the `div`s with non-empty `data-title` attributes. But after applying _postcss-preset-env_ this code becomes `div[data-title]:not([data-title]) { ... }` (the `=""` is dropped). So, the rule becomes self-exclusive.

I wonder if such a behaviour of the tool is reasonable or it's a bug?

**Comment by a-t** [comment]
I tried both with single and double quotes.

**Comment by jonathantneal** [comment]
I recently resolved an issue in one of the plugins this project uses that may have also resolved this. Would you re-test in 5.2.1?

Your code looks right to me at https://preset-env.cssdb.org/playground

**Comment by a-t** [comment]
The issue has gone for now. Thanks a lot! The problem was indeed caused by _postcss-attribute-case-insensitive_ prior to 3.0.1.
