### ISSUE TITLE
Webpack instructions: import instead of const

### ISSUE THREAD

**Issue by onetrev** [csstools/postcss-preset-env#45]
Definitely I am pretty new to webpack, but when I tried:

`import postcssPresetEnv from 'postcss-preset-env';`

I receive an error msg of: _SyntaxError: Unexpected token import_ .  From my experience don't most plugins load like so:

`const postcssPresetEnv = require('postcss-preset-env');`

Related question, but slightly off topic, does it work if I add postcssPresetEnv to my `postcss.config.js` file instead of using the _identifier_ in your main webpack.config? Seems like most other PostCSS plugins suggest the config file method in their webpack docs.

**Comment by jonathantneal** [comment]
@onetrev, I’m unsure which environment people will be loading these plugins, so I posted what seems at this time like the most straight-forward solution.

I’m happy to update the README.md to follow better practices. Would you link me to some other documentation doing it consistently another way, or even just another way you find easier? I will happily evaluate it.

**Comment by onetrev** [comment]
Gotcha, ya no worries. With webpack, there are often so many different ways to go, and I'm very far from an expert.

An example for you, with what has to be the most popular (famous?) PostCSS plugin -- autoprefixer -- so probably a good reference, they recommend the [separate file setup](https://github.com/postcss/autoprefixer#webpack) I was suggesting. Hope that helps!

**Comment by jonathantneal** [comment]
For now, I will keep the documentation the same, following a single syntax for consistency and to avoid odd behaviors/bugs.

**Comment by onetrev** [comment]
No worries. Though as noted `import postcssPresetEnv from 'postcss-preset-env';` results in that syntax error I mentioned.
