### ISSUE TITLE
postcss-preset-env removes empty quotes

### ISSUE THREAD

**Issue by nickbullock** [csstools/postcss-preset-env#46]
Hi, guys.
I have a complicated case, i use webpack v4 with less-loader and postcss-loader (with postcss-preset-env),
so less rule for production build looks like this: 
```
 {
          test: /\.less$/,
          use: [
            MiniCssExtractPlugin.loader,
            cssLoader(opts.sourceMap),
            postCssLoader(opts.sourceMap),
            lessLoader(opts.sourceMap)
          ]
}
```
, and postcss-loader options
```
function postCssLoader(sourceMap) {
  return {
    loader: 'postcss-loader',
    options: {
      ident: 'postcss',
      plugins: () => [
        require('postcss-preset-env')(),
        require('postcss-flexbugs-fixes')()
        require('css-mqpacker')(), 
        require('postcss-csso')()
      ]
    }
  };
}
```
and when postcss processes .less file with 
```
...styles
    &.super-div[required] .super-div__input[value=''] {
     backgroud: red;
    }
...another styles
``` 
in extracted css file i can see

```
  &.super-div[required] .super-div__input[value] {
     backgroud: red;
    }
```
 and it kills styles for me =)
If i remove preset-env from plugins list, output is compiled correctly.

I will create a minimal reproduction repo as soon as i can.

**Comment by jonathantneal** [comment]
Hi @nickbullock, would you consider updating the plugin? This may be a duplicate of #44, which resolves Semigradsky/postcss-attribute-case-insensitive#22.

**Comment by nickbullock** [comment]
@jonathantneal thank you! it's works now.
