### ISSUE TITLE
CSS nesting not working with VueJS

### ISSUE THREAD

**Issue by andreynazarov3** [csstools/postcss-preset-env#47]
Hello, I am new to PostCSS so I may be missing something. Sorry if I am doing something stupid here.
I was struggling couple of hours trying to make CSS nesting working but it is not working.
This maybe due to `"postcss-nesting"` plugin.
I tried using config in `package.json` like this: 
```
"postcss": {
    "plugins": {
      "postcss-preset-env": {
        "stage": 0
      }
    }
  }
```
FInally I found that postcss-nested" plugin is working so maybe you should switch to this plugin instead of `"postcss-nesting"`:
```
"postcss": {
    "plugins": {
      "postcss-nested": {
      }
    }
  }
```
Last thing: I am using Vue CLI (like react create app) so I don't see webpack config there.

**Comment by jonathantneal** [comment]
You haven’t shared any CSS that is not working, so unfortunately, I can’t provide specific help. I’ll share two possibilities anyway to try and help you.

1. Are you using selector nesting according to the spec?
   - https://tabatkins.github.io/specs/css-nesting/#direct
   - https://tabatkins.github.io/specs/css-nesting/#at-nest
   - https://cssdb.org/#nesting-rules

```pcss
.some-selector {
  & .some-descendant {
    /* this is good */
  }

  @nest body & {
    /* this is good */
  }
}
```

```pcss
.some {
  &-selector {
    /* this wont work, and sass may soon deprecate this, too */
  }
}

.some-selector {
  body & {
    /* this wont work, because the first character must be & or @nest */
  }
}
```

2. Staging is a Stage 0 feature. Have you enabled Stage 0 features? 

   - https://github.com/csstools/postcss-preset-env#stage
   - https://cssdb.org/#staging-process

```js
import postcssPresetEnv from 'postcss-preset-env';

postcssPresetEnv({
  stage: 0
})
```

**Comment by ivomarsan** [comment]
@jonathantneal I think he meant that your `postcss-preset-env` is not working.

Well, I'll try to explain my case. In my Vue Application I have the following CSS snippet
```postcss
a {
  color: red;

  &:hover {
    color: blue
  }
}
```
First, should I use in the `lang` attribute from `<style scoped>` the `css` or `postcss` option?
Second, in the `.postcssrc.js` file I should do some configuration besides:
```javascript
module.exports = {
  plugins: {
    'postcss-preset-env': {},
    autoprefixer: {},
  }
}
```
Because even after `npm i postcss-preset-env` I can not get functional result in my `a:hover`. So, help-me to config my postcss in vue-cli boilerplate.
