### ISSUE TITLE
Custom properties config with color-mod function

### ISSUE THREAD

**Issue by Cherry** [csstools/postcss-preset-env#48]
When using postcss-preset-env, and specifically the `postcss-color-mod-function` and `postcss-custom-properties` plugins together, an unexpected result happens when using the `variables` configuration option from `postcss-custom-properties`.

In [this repo](https://github.com/Cherry/test-postcss-color-mod-variables), you'll find 2 simple css files, and 2 build scripts with gulp to replicate the issue. The expected result of both tests is to complete successfully, with the `color-mod` function executing without error.

## npm run build-withRoot

This is the test that works fine, and the more simple scenario. The https://github.com/Cherry/test-postcss-color-mod-variables/blob/master/src/test-withRoot.css file defines a `:root`  block with a variable `--black`, and then we use that variable in a `color-mod` function directly underneath. This works fine (although the output is strangely duplicated).

## npm run build-withVariablesConfig

This example does not work with `color-mod`, but other uses of the variable work fine. This method of defining variables in the `variables` configuration option is very useful for larger projects with a lot of variables, or thousands of css files that don't wish to import the variables every single time.

If you run this script, you'll receive an error akin to `test-withVariablesConfig.css:2:30: Expected a color`.

-----
We're transitioning from `postcss-cssnext` and it's been extremely smooth up to this point, as this used to work fine in the past. I'd imagine it's a simple load order thing, but I couldn't quite find the issue at a quick glance.

Let me know if I can provide any further information to help here.

https://github.com/Cherry/test-postcss-color-mod-variables

**Comment by wadehammes** [comment]
I'm also getting an error similar to this. `:root` variables are not getting parsed in the `color-mod()` arguments:
```
Message:
    precss: /code/app/assets/css/components/switch.css:35:64: Expected valid shade() arguments

  33 |       background: var(--switch-button-color);
  34 |       border-radius: 1000px;
> 35 |       box-shadow: 0 1px 0 color-mod(var(--switch-button-color) shade(var(--switch-shade)));
     |                                                                ^
```

**Comment by jonathantneal** [comment]
@Cherry, thanks for bringing this to my attention. I have a solution for you, and then an explanation of the problem.

First, you can work-around this limitation in `postcss-color-mod-function` by instructing it to ignore unresolved variables like so:

```js
postcssPresetEnv({
  features: {
    'color-mod-function': {
      unresolved: 'ignore'
    }
  }
})
```

Second, this is happening because `postcss-color-mod-function` tried to resolve variables it could not find. It resolves variables at build time because they cannot be otherwise resolved and adjusted at runtime. This is a limitation of `color-mod()`. Because you are passing variables directly to `postcss-custom-properties`, this means that `postcss-color-mod-function` never finds them in `:root` or `html`. The default behavior in `postcss-color-mod-function` is to throw when this happens. That is, perhaps, a bad default.

If you’re wondering why `postcss-custom-properties` didn’t already resolve these variables — it did. However, it also left a copy of the original declaration for modern browsers. It’s that secondary, modern declaration that `postcss-color-mod-function` failed to resolve.

**Comment by Cherry** [comment]
Thanks, this definitely provides a lot more insight as to what we're seeing.

I've run into another issue with this though, and `color-mod` seemingly being a little too generous about the browsers it supports. As a basic example, I've set `browsers` to `last 3 chrome versions`, and this results in `color-mod` functions never being resolved, even though this functionality isn't built into chrome yet (or any browser as far as I know).

I've updated the repo so you can debug this further.

PS. Is there any way to force a polyfill to run, even if the features specified are supported in the `browserslist` query? This would be a quick work-around to this issue.

**Comment by jonathantneal** [comment]
@Cherry, no browsers support color-mod, and the cssdb.json file confirms this:

https://github.com/csstools/cssdb/blob/master/cssdb.json#L76-L89

Is this something test-able on the playground?

**Comment by jonathantneal** [comment]
I have a theory. If you specify `last 3 chrome versions` then `postcss-custom-properties` will never run, which means you’ll never get those variables you’ve defined in JS, which means you’ll never resolve your `color-mod()` adjusters using those variables. Does this seem right?

**Comment by Cherry** [comment]
That sounds possible. I understand that no browsers support `color-mod` yet - we want those to be resolved to direct colours.

So for example, if we specified:
```browsers: 'last 3 chrome versions'```
I'd expect `color: var(--black)` to not be transformed and output as `color: var(--black)`, but `color-mod(var(--black) alpha(20%))` should be transformed to something like `color: rgba(0, 0, 0, 0.2)`.

If I manually call `postcss-custom-properties` first outside of `postcss-preset-env`, this resolves the issue (as it always run and doesn't take into account any `browsersconfig`. If we could force polyfills to always run, similarly to how is possible in `babel-preset-env`'s `include` config, that would take care of these edge-cases I'd imagine.

**Comment by jonathantneal** [comment]
@Cherry, this appears to be a bug.

> Passing `true` to a specific feature id will enable its polyfill, while passing `false` will disable it.
> Passing an object `{}` to a specific feature id will enable and configure it.

The first filter, based on stage, handles this correctly:
https://github.com/csstools/postcss-preset-env/blob/master/index.js#L59

The second filter, based on browserslist, handles this incorrectly:
https://github.com/csstools/postcss-preset-env/blob/master/index.js#L83-L89

I will patch this and release a new version.

**Comment by mrmckeb** [comment]
@jonathantneal Was this fix released? It still seems to be a problem.

**Comment by feimosi** [comment]
I've managed to work around it by including `postcss-color-mod-function` separately at the end of the PostCSS plugins list.

**Comment by jonathantneal** [comment]
Since Color Mod is now a rejected spec, you'll need to use insertBefore/After.
