### ISSUE TITLE
Semicolons with @apply rules and nested selectors aren't kept

### ISSUE THREAD

**Issue by neoel** [csstools/postcss-preset-env#50]
I'm using postcss-import and postcss-preset-env (stage 0). [postcss@^6.0, postcss-import@^11.1.0, postcss-preset-env@^5.2.1]

I'm importing some custom property sets, and somewhere in the process it's going wrong.

This
```
  progress[value] {
    @apply --progress-bar;

    &::-moz-progress-bar {
      @apply --progress-value;
    }
  }
```

Is being turned into 
```
3985:   progress[value] {
3986:     @apply --progress-bar
3987:   }
```

I'm also wondering why (after postcss processing), the @apply rule is still present here.

**Comment by pascalduez** [comment]
@neoel The `postcss-apply` plugin is not part of `postcss-preset-env` since it's a rejected spec.

**Comment by neoel** [comment]
Ah thanks, I didn't know that. 
I quite like the idea of being able to import some definitions (custom property sets) and applying them to my components. I've looked a bit around, but I haven't found any feature which could mimic this behaviour. 
Have you got an idea?

**Comment by pascalduez** [comment]
@neoel You can still add the `postcss-apply` plugin to your postcss flow, after the `postcss-preset-env` I would say. But that means relying on a syntax/feature that will most likely never see the light. There's currently no new spec for a similar behaviour.  
There is also a `postcss-mixin` plugin, more Sass like.
