### ISSUE TITLE
postcss-color-gray not included

### ISSUE THREAD

**Issue by robjtede** [csstools/postcss-preset-env#51]
Despite being listed as a feature in the docs, I was unable to use the `gray(x)` notation after upgrading from cssnext. Looking at the `package.json` and code it doens't mention the `postcss-color-gray` package anywhere.

Using
```
html {
  color: gray(50);
}
```
on the [playground](https://preset-env.cssdb.org/playground) didn't work either...

<img width="659" alt="2018-07-22_22 36 28-edb95d90" src="https://user-images.githubusercontent.com/3316789/43050391-cf6ccb9e-8dff-11e8-9295-9c0cc51b588c.png">

**Comment by jonathantneal** [comment]
Thanks for bringing this to my attention. I will try to create or update the existing `gray` plugin as soon as possible.

It looks like it was missed because the functionality in cssnext was incorrect:

https://github.com/postcss/postcss-color-gray/issues/11

**Comment by jonathantneal** [comment]
@robjtede, I’ve added it via `postcss-lab-function` and published it in v5.2.0!
