### ISSUE TITLE
Documentation does not mention `postcss-preset-env` includes autoprefixer

### ISSUE THREAD

**Issue by halfzebra** [csstools/postcss-preset-env#55]
It would be nice to mention that in the `README.md` and probably on the website https://preset-env.cssdb.org/

Like it was done in http://cssnext.io/features/#automatic-vendor-prefixes

I'm interested in sending a PR if this makes sense.

**Comment by jonathantneal** [comment]
Yes, this should also be documented.

**Comment by halfzebra** [comment]
Thanks for the reply!

What about the website?

Would it make sense to send a PR to https://github.com/csstools/postcss-preset-env-www ?
