### ISSUE TITLE
Example of configuring postcss-preset-env with postcss.config.js

### ISSUE THREAD

**Issue by halfzebra** [csstools/postcss-preset-env#56]
The README.md has an exhaustive documentation of configuring postcss-preset-env for popular build tools, but it does not mention that it's possible to use `postcss.config.js`

Maybe it has to be addressed in https://github.com/postcss/postcss-loader instead, please feel free to close this if you don't find int relevant.

**UPD:**

The reasoning for this is that the examples use the notation with the function `postcssPresetEnv(/* options */)`, while it's possible to pass plugins in a bunch of different ways.

**Comment by jonathantneal** [comment]
Yea, this should be documented.

**Comment by halfzebra** [comment]
I have addressed this in https://github.com/postcss/postcss-loader repo already by updating the documentation to include `postcss-preset-env` as a default solution, I'll send a PR shortly with the example of setup with `postcss.config.js`

**Comment by nathanchase** [comment]
This is an example of a **postcss.config.js** that incorporates **postcss-preset-env**:
```
const postcssPresetEnv = require('postcss-preset-env')
const config = () => ({
  plugins: [
    postcssPresetEnv({
      stage: 0
    })
  ]
})
```
