### ISSUE TITLE
Update to PostCSS 7

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#58]
- **Total number of plugins**: 29
- **Number of plugins that need to be updated**: 28

| PostCSS Plugin | Upgraded to PostCSS 7 |
| --- | --- |
| autoprefixer | ✔ |
| postcss-attribute-case-insensitive | |
| postcss-color-functional-notation | |
| postcss-color-hex-alpha | |
| postcss-color-mod-function | |
| postcss-color-rebeccapurple | |
| postcss-custom-media | |
| postcss-custom-properties | |
| postcss-custom-selectors | |
| postcss-dir-pseudo-class | |
| postcss-env-function | |
| postcss-focus-visible | |
| postcss-focus-within | |
| postcss-font-family-system-ui | |
| postcss-font-variant | |
| postcss-gap-properties | |
| postcss-image-set-function | |
| postcss-initial | |
| postcss-lab-function | |
| postcss-logical | |
| postcss-media-minmax | |
| postcss-nesting | |
| postcss-overflow-shorthand | |
| postcss-page-break | |
| postcss-place | |
| postcss-pseudo-class-any-link | |
| postcss-replace-overflow-wrap | |
| postcss-selector-matches | |
| postcss-selector-not | |

**Comment by pascalduez** [comment]
@jonathantneal Do you needs a hand on this?

**Comment by MattDiMu** [comment]
postcss-replace-overflow-wrap dependencies have been updated, adjusted to the current eslint-config-postcss rules and published as v3.0 https://www.npmjs.com/package/postcss-replace-overflow-wrap

**Comment by ansballard** [comment]
Would it help to get some PRs to update the remaining plugins to 7? I put in a PR for postcss-nesting since that's mostly what I use, but if this wrapper plugin can be updated that would be ideal.

Thanks for the tools!

**Comment by ansballard** [comment]
Looks like a few on the packages on the list were upgraded a couple days ago, I'll list what I found already done here, and I'll see about putting in PR's for the rest

## Already Upgraded to PostCSS@7

- postcss-color-hex-alpha
- postcss-color-rebeccapurple
- postcss-custom-media
- postcss-custom-properties
- postcss-custom-selectors
- postcss-font-family-system-ui
- postcss-nested
- postcss-pseudo-class-any-link
- postcss-replace-overflow-wrap
- postcss-selector-matches
- postcss-selector-not

## TODO

- postcss-dir-pseudo-class
- postcss-env-function
- postcss-focus-visible
- postcss-focus-within
- postcss-font-variant (real old)
- postcss-gap-properties
- postcss-image-set-function
- postcss-initial (old)
- postcss-lab-function
- postcss-logical
- postcss-overflow-shorthand

## PR Needs Merging
- postcss-attribute-case-insensitive
- postcss-color-functional-notation
- postcss-color-mod-function
- postcss-nesting
- postcss-media-minmax (Not Me)
- postcss-page-break (Not Me)
- postcss-place (Not Me)

**Comment by pieterbeulque** [comment]
Hi @ansballard,

Here's an update to @ansballard their list:

## Already Upgraded to PostCSS@7
postcss-color-hex-alpha
postcss-color-rebeccapurple
postcss-custom-media
postcss-custom-properties
postcss-custom-selectors
postcss-font-family-system-ui
postcss-nested
postcss-pseudo-class-any-link
postcss-replace-overflow-wrap
postcss-selector-matches
postcss-selector-not
postcss-attribute-case-insensitive
postcss-nesting
postcss-page-break
postcss-dir-pseudo-class
postcss-env-function
postcss-focus-visible
postcss-focus-within
postcss-font-variant
postcss-gap-properties
postcss-image-set-function
postcss-initial
postcss-lab-function
postcss-logical
postcss-overflow-shorthand

## PR Needs Merging/Releasing
postcss-color-functional-notation
postcss-color-mod-function
postcss-media-minmax
postcss-place

**Comment by jonathantneal** [comment]
Resolving via https://github.com/csstools/postcss-preset-env/pull/73
