### ISSUE TITLE
Document available features with plugin names

### ISSUE THREAD

**Issue by halfzebra** [csstools/postcss-preset-env#60]
It's easy to see which features are available on https://preset-env.cssdb.org/features, but in a scenario where I want to have Stage 3 features along with just one from Stage 1 enabled explicitly, it's hard to figure out what  specific key unless I'll look directly into [/lib/plugins-by-id.js](https://github.com/csstools/postcss-preset-env/blob/2f71263584cca63d100b9814a50b05b0564ef401/lib/plugins-by-id.js)

 I think it would make sense to list them in the documentation, or maybe create a script that looks into [/lib/plugins-by-id.js](https://github.com/csstools/postcss-preset-env/blob/2f71263584cca63d100b9814a50b05b0564ef401/lib/plugins-by-id.js) and writes `FEATURES.md` with keys?

The reason why it's a bit confusing is that some plugin names have changed and they are hard to map onto a human-readable feature name from https://preset-env.cssdb.org/features

I'm up for doing the PR if this makes sense 🙂

**Comment by jonathantneal** [comment]
I would accept a PR, though it might make more sense to do this in the www repo.
