### ISSUE TITLE
color-mod() function rejected

### ISSUE THREAD

**Issue by rojlarge** [csstools/postcss-preset-env#71]
It looks like the `color-mod()` function has been rejected: (https://github.com/w3c/csswg-drafts/commit/034b063697c3dadf144504f52e0858a79cd84414) and bumped down to stage -1 in `cssdb`: (https://github.com/csstools/cssdb/commit/96bb8e8547a946dcbc29b866ac13330fed6ca04b).

Do the docs need to be updated to reflect this? My team spent a while this morning trying to figure out why color-mod was no longer working with any stage config. Are there any plans to replace this function with something else for adjusting colors?

Thanks!

**Comment by jonathantneal** [comment]
The docs will be updated to reflect this. Tests are updated. Resolving via https://github.com/csstools/postcss-preset-env/pull/73

**Comment by the-spyke** [comment]
@jonathantneal I think that should be done as a major version bump, because the update silently broke projects.
