### ISSUE TITLE
Fallback for CSS variable assigned to a CSS variable

### ISSUE THREAD

**Issue by martinmethod** [csstools/postcss-preset-env#72]
If I have this code:

```
:root {
    --col-light: #fff;
    --main-background: var(--col-light);
}

body {
    background-color: var(--main-background);
}
```

The output will be like so:

```
:root {
    --col-light: #fff;
    --main-background: #fff; // a fallback value where it's not needed
    --main-background: var(--col-light);
}

body {
    color: var(--main-background);
}
```

I expect the compiler to pass the first variable's value (#fff) through the second variable to the property and to have an output like this one:

```
:root {
    --col-light: #fff;
    --main-background: var(--col-light);
}

body {
    color: #fff; // a properly placed fallback value
    color: var(--main-background);
}
```

Because now the outcome makes the Fallback feature useless.

**Comment by bryancasler** [comment]
@methodev I know it's been three years but I'm running into this too. What did you do to resolve this?

**Comment by methodev** [comment]
> @methodev I know it's been three years but I'm running into this too. What did you do to resolve this?

@bryancasler Don't remember, frankly. I think I just abandoned it.
