### ISSUE TITLE
postcss-env-function not actually loaded

### ISSUE THREAD

**Issue by joelmoss** [csstools/postcss-preset-env#75]
Upgraded to the latest and greatest (6.0.0), and even though it says that `postcss-env-function` is included, it's not in https://github.com/csstools/postcss-preset-env/blob/master/lib/plugins-by-id.js

Am I missing something? thx

**Comment by jonathantneal** [comment]
Wow, what a wonderful catch. Do you suppose this means you were the first person who really wanted to use it? 😄

I’ve fixed this in 6.0.2, and I’ve added a fun test for it.

https://github.com/csstools/postcss-preset-env/blob/master/.tape.js#L124-L143
https://github.com/csstools/postcss-preset-env/blob/master/test/import.css
https://github.com/csstools/postcss-preset-env/blob/master/test/import.expect.css
