### ISSUE TITLE
color-mod() not converted as expected

### ISSUE THREAD

**Issue by martinmethod** [csstools/postcss-preset-env#76]
I have the following definition for example:

```
body {
  border-color: color-mod(yellow blend(red 50%));
}
```

and the output remains:

```
body {
  border-color: color-mod(yellow blend(red 50%));
}
```

instead of:

```
body {
  border-color: rgb(255, 127.5, 0);
}
```

Here's [my TestApp repository](https://github.com/martinmethod/testapp) that you can clone, install, run (`yarn serve:dev`) and review the output css definitions for the `<body>` element in Chrome Dev Toolbar.

Please, give it a look and say if I'm missing something or doing something wrong or something else breaks it.

**Comment by pascalduez** [comment]
It's been rejected, so you'd have specifically include the plugin now.   

See https://github.com/csstools/cssdb/commit/96bb8e8547a946dcbc29b866ac13330fed6ca04b

**Comment by martinmethod** [comment]
> It's been rejected, so you'd have specifically include the plugin now.
> 
> See [csstools/cssdb@96bb8e8](https://github.com/csstools/cssdb/commit/96bb8e8547a946dcbc29b866ac13330fed6ca04b)

It worked. Thanks for the info. :)
