### ISSUE TITLE
Nesting not working

### ISSUE THREAD

**Issue by martinmethod** [csstools/postcss-preset-env#77]
I have the following definition for example:

```
a {
  color: rgb(0 0 100% / 90%);

  &:hover {
    color: rebeccapurple;
  }
}
```

and the output seen in the Chrome Dev Toolbar [looks like this](https://www.dropbox.com/s/xykvrkszwtac80h/Screenshot%202018-09-21%2015.36.31.png?dl=0).

--
Here's [my TestApp repository](https://github.com/martinmethod/testapp) that you can clone, install, run (`yarn serve:dev`) and review the output css definitions for the only `<a>` element in Chrome Dev Toolbar.

Please, give it a look and say if I'm missing something or doing something wrong or something else breaks it.

**Comment by pascalduez** [comment]
Nesting rules is at a Stage 0 level, so you'd have to specifically include the plugin. 
`postcss-preset-env` starts at Stage 2.  
See https://cssdb.org/#nesting-rules

**Comment by martinmethod** [comment]
> Nesting rules is at a Stage 0 level, so you'd have to specifically include the plugin.
> `postcss-preset-env` starts at Stage 2.
> See https://cssdb.org/#nesting-rules

I haven't checked that.
Great! Thanks! :)
