### ISSUE TITLE
Custom property assigned to custom property does not print fallback values

### ISSUE THREAD

**Issue by martinmethod** [csstools/postcss-preset-env#78]
I have three separate CSS files and each of them has defined CSS variables in `:root {}` level.

All three files are given to the **importFrom** option, where the second and the third CSS files have defined variables with values equal to variables that comes from the first given file.

The output is not as expected which means:
1. There are no printed variables in `:root {}` at all.
2. Properties that uses variable which value is another variable doesn't have fallback value.

--
Here's [my TestApp repository](https://github.com/martinmethod/testapp) that you can clone, install, run (`yarn serve:dev`) and review the output css definitions for the `<body>` element in Chrome Dev Toolbar.

Please, give it a look and say if I'm missing something or doing something wrong or something else breaks it.

**Comment by jonathantneal** [comment]
First, thank you for reporting an issue in a clear way, with a solid explanation and a repo to reproduce the issue. I only had a moment to checkout your work, but I may have identified the issue:

![image](https://user-images.githubusercontent.com/188426/45888450-12021e80-bd8c-11e8-91fe-d232469783e3.png)

I see you are using `color-mod`, which has been removed as a standard by the CSSWG. Some of your colors may not be working because of this. You’ll have to manually activate the now non-standard feature.

```
    // convert modern CSS into something most browsers can understand
    require('postcss-preset-env')({
      importFrom: [
        './client/src/styles/data/swatches/swatches_colors.css',
        './client/src/styles/data/swatches/swatches_backgrounds.css',
        './client/src/styles/data/roles/roles_colors.css'
      ],
      features: {
        'color-mod-function': true
      }
    })
```

And here is the result:

![image](https://user-images.githubusercontent.com/188426/45888677-a53b5400-bd8c-11e8-81c7-971ad176fe17.png)

I’ll leave this issue open if you are experiencing further issues.

**Comment by jonathantneal** [comment]
I noticed that you never import your swatches into the central app, which means browsers supporting `var()` never get a chance to use them.

What is the reason you want to use custom variables but not include them?

If you wish for these values to be hidden from the user, I’d recommend using `env()` instead.

**Comment by martinmethod** [comment]
Hey @jonathantneal,
Thanks for the quick response. :)

Regarding the **color-mod-function** – I got that, I set the feature to true and it works now.

However, my question here is more about the background-color value.

You can see in your screenshot above that `background-color` doesn't actually have a fallback definition above the one with the variable value.

So just as the **color** property is printed like so:

```
color: #36c
color: var(--mainColor)
```

I expect the **background-color** property to be printed like this:

```
background-color: #333
background-color: var(--swatch-bgr-mine-shaft)
```

And even though I import that variable alongside some others as it, there is absolutely nowhere printed in the output the following definition:

```
:root {
   --swatch-bgr-mine-shaft: var(--swatch-col-mine-shaft);
}
```

nor even this one:

```
:root {
   --swatch-col-mine-shaft: #333;
}
```

You can see that in Chrome Dev Tools.

I import three files containing lots of variables, where some of them are pointing to other variables, just like this case.

**Comment by jonathantneal** [comment]
> I import three files containing lots of variables, where some of them are pointing to other variables, just like this case.

If you intend to support custom properties, you’ll need to include the custom properties somewhere in your global CSS. Otherwise, the custom property references will overwrite the fallbacks, but since those references are missing nothing will change.

#### Example

```
body {
  background-color: blue;
  background-color: var(--unresolved-variable);
}
```

Browsers supporting `var()` will get a white background. You can test this in plain CSS without ever using PostCSS Preset Env.

This is why I asked about how you intend to use these variables. If you intend to hide them from the browser, consider using `env()`.

**Comment by martinmethod** [comment]
> This is why I asked about how you intend to use these variables. If you intend to hide them from the browser, consider using `env()`.

Well, no, not at all. I'm completely fine for the variables to be visible and public, so I'm looking for var() and not env().

As to the including – yeah, I got that now and I import them in index.js right before scaffolding.css. So now I see all variables definitions in `:root {}` printed in the output.

However `background-color` still doesn't have it's fallback definition with static hex value. You can reproduce that with my recent pushed commits. If you have time, of course. :)

**Comment by jonathantneal** [comment]
Two more unrelated things that I hope will help you.

1. Because you are using nesting, be sure you pass a stage into your options. UPDATE: It looks like you’ve recently added this. Awesome!

2. Because you are using `color-mod()`, be sure you pass your imports into this plugin as well.

```
const cssImports = [
  './client/src/styles/data/swatches/swatches_colors.css',
  './client/src/styles/data/swatches/swatches_backgrounds.css',
  './client/src/styles/data/roles/roles_colors.css'
];

module.exports = {
  plugins: [
    // transform @import rules by inlining content
    require('postcss-import'),

    // convert modern CSS into something most browsers can understand
    require('postcss-preset-env')({
      stage: 0,
      importFrom: cssImports,
      features: {
        'color-mod-function': {
          importFrom: cssImports
        }
      }
    })
  ]
};
```

**Comment by jonathantneal** [comment]
![image](https://user-images.githubusercontent.com/188426/45894467-6e6d3a00-bd9c-11e8-9188-b76ed7fc468f.png)

Everything looks correct to me here. Are you still having any issues?

**Comment by martinmethod** [comment]
> Everything looks correct to me here. Are you still having any issues?

Just deleted `node_modules` dir and yarn.lock and made fresh `yarn install` and it worked. Wicked!

You're awesome. Thanks a lot for the help. I'm really thrilled to use custom variables.
