### ISSUE TITLE
create-react-app already includes postcss-preset-env by default

### ISSUE THREAD

**Issue by heygrady** [csstools/postcss-preset-env#82]
- https://github.com/facebook/create-react-app/pull/4716
- https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L61-L65
- https://github.com/csstools/postcss-preset-env/blob/master/INSTALL.md#create-react-app

The docs are probably out of date. Rewire would still be useful for customizing the defaults, but it's probably worth mentioning that create-react-app ships with postcss-preset-env already enabled.

**Comment by jonathantneal** [comment]
Create React App 2 has been released, so I will now update the documentation.

**Comment by jonathantneal** [comment]
Resolved in 6.0.8 😄
