### ISSUE TITLE
custom-properties no longer applied after upgrade to CRA2

### ISSUE THREAD

**Issue by bdefore** [csstools/postcss-preset-env#84]
After updating to the new CRA2, I'm no longer seeing custom properties applied. Not sure if the issue resides in postcss-present-env or react-app-rewire-postcss.

My configuration in react-app-rewired is unchanged from:

```
  const variables = require('./src/css/variables.json')
  const mediaQueries = require('./src/css/media-queries.json')

  config = rewirePostcss(config, {
    plugins: () => [
      // postcssPresetEnv(/* allow postcss.config.js to configure */)
      postcssPresetEnv({
        stage: 0,
        features: {
          'custom-media-queries': { extensions: mediaQueries },
          'custom-properties': {
            preserve: false,
            variables: variables
          }
        }
      })
    ]
  })

  // with the following line, custom properties works with ^5.3.0 but not ^6.0.8. without this line, using CRA2 built in CSS Modules support, does not work at all (strange?)
  config = rewireCssModules(config, env) 
```

The relevant deltas in my dependencies are:
```
    "postcss-preset-env": "^6.0.8" (up from ^5.3.0)
    "react-app-rewire-postcss": "^2.0.0" (up from ^1.0.2)
    "react-scripts": "2.0.3" (up from ^1.1.5)
```
(I have left react-app-rewired unchanged at `^1.6.2`)

Maybe relevant: https://github.com/csstools/react-app-rewire-postcss/issues/4

**Comment by bdefore** [comment]
Forgot to mention, I'm have also been using https://github.com/codebandits/react-app-rewire-css-modules for CSS Modules support and my calls to `var(--variableName)` are made within files with `module.css` extension. I'll add the configuration line to the initial comment above.

This functionality has been newly been bundled in with CRA2 but does not appear to cooperate with custom properties. Along with upgrading the other dependencies, postcss-present-env of `^5.3.0` functions as expected but `^6.0.8` does not.

**Comment by jonathantneal** [comment]
We need to move this issue over to https://github.com/csstools/react-app-rewire-postcss as Create React App 2 is not something you can configure, AFAIK, while the features you are looking to use probably still require React App Rewire PostCSS.

**Comment by bdefore** [comment]
This issue was moved to csstools/react-app-rewire-postcss#5
