### ISSUE TITLE
@custom-media not working with "and"

### ISSUE THREAD

**Issue by jonathandion** [csstools/postcss-preset-env#94]
I'm facing issues using `@custom-media` with `and` 

```
@custom-media --at-bp-medium-low-only (width >= 34.375em) and (width < 47.5em);

body {
  background-color: red;
  @media (--at-bp-medium-low-only) {
    background: blue;
  }
}
```
The media query is never triggered

**Comment by jonathantneal** [comment]
Thanks for reporting this. It’s just been fixed in v6.1.2.

I’m releasing 6.2.0 shortly to take in the minor semver updates from autoprefixer. 😄
