### ISSUE TITLE
Forgot to publish 6.2.0?

### ISSUE THREAD

**Issue by Cretezy** [csstools/postcss-preset-env#95]
I see you created the tag for 6.2.0, but it seems to be missing from npm. Did you forget to publish it? :stuck_out_tongue:

**Comment by jonathantneal** [comment]
Wonderful catch. It was good fortune that I forgot to publish it, because `browserslist` has also released a minor update, so I can now slip in both.

**Comment by jonathantneal** [comment]
It is now published! 🎉

Thank you again for bringing this to my attention.
